### ISSUE TITLE
NavbarBrand doesn't accept Link as tag

### ISSUE THREAD

**Issue by o1dnik** [coreui/coreui-react#100]
Using the following:

```
      <AppNavbarBrand
        tag={Link}
      />
```
will throw warning message: "Warning: Failed prop type: Invalid prop `tag` supplied to `AppNavbarBrand`.". I didn't find out how to pass a custom clickable Link component. Can you suggest?

**Comment by xidedix** [comment]
Hi @o1dnik 
What about:
```jsx
<AppNavbarBrand
  tag={NavLink}
  to="/users"
  full={{ src: logo, width: 89, height: 25, alt: 'CoreUI Logo' }}
  minimized={{ src: sygnet, width: 30, height: 30, alt: 'CoreUI Logo' }}
/>
```

**Comment by o1dnik** [comment]
@xidedix I've tried with `NavLink` before creting this issue because I read your suggestion in another thread. But it does not work either. Here's the exact snippet of what we use:

```
      <AppNavbarBrand
        tag={Link}
        to={reverse(urls.dashboard)}
        full={{ src: logo, width: 40, height: 40, alt: "..." }}
        minimized={{ src: logo, width: 40, height: 40, alt: "..." }}
      />
```
where `reverse` function just returns a string (correct for router).

**Comment by xidedix** [comment]
@o1dnik 
Let's try this way:
```jsx
<Link to={'/users'}>
  <AppNavbarBrand
    tag={'div'}
    full={{ src: logo, width: 40, height: 40, alt: "..." }}
    minimized={{ src: logo, width: 40, height: 40, alt: "..." }}
  />
</Link>
```

**Comment by o1dnik** [comment]
Yep, this workaround works fine, though I thought I could pass the component as `Tag` to be rendered. Thank you for the suggestion
