### ISSUE TITLE
Attempted import error: 'Arrow' is not exported from 'react-popper'.

### ISSUE THREAD

**Issue by KimWooHyun** [coreui/coreui-react#103]
I installed the package @coreui/react(^3.0.0-alpha.3), but I'm getting this error, any sugestion?

![image](https://user-images.githubusercontent.com/4816936/75236472-2b20c180-5801-11ea-8b6a-2734bae62fc3.png)

I used 
```
"react": "^16.12.0",
"reactstrap": "^8.4.1",
"@coreui/react": "3.0.0-alpha.3",
```

It looks similar to [this](https://github.com/coreui/coreui-free-react-admin-template/issues/189)

**Comment by xidedix** [comment]
Hi @KimWooHyun 

@coreui/react 3.0.0-alpha.3 well... it's alpha...
it uses an older version of `react-popper` than reactstrap

**Comment by KimWooHyun** [comment]
Hi @xidedix 
Thanks for the reply.

If so, will it take long to patch...? 😢
I want to use coreui-pro 3.0(already buying) with typescript, react

**Comment by KimWooHyun** [comment]
I saw in the [blog](https://coreui.io/blog/2019/11/06/are-you-ready-for-coreui-3.0/) that TypeScript is supported since CoreUI 3.0.

**Comment by joaquinmerlo** [comment]
I have the same issue. did you find a solution?

**Comment by woothu** [comment]
`react-popper` is no longer used in Dropdown components in stable versions. (Issue is solved)

**Comment by Touseef-haider** [comment]
Attempted import error: 'CBadge' is not exported from '@coreui/react'.
I am getting this error while I have imported it in a right way. I am using coreui version ^3.4.6
