### ISSUE TITLE
compilation error with nextJS

### ISSUE THREAD

**Issue by gaurav517** [coreui/coreui-react#107]
We can't compile when using nextJS:
```
[ wait ]  compiling ...
[ error ] /Users/user/Documents/myproject/client/node_modules/react-perfect-scrollbar/dist/css/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: ../../@coreui/react/es/SidebarNav.js
```
More information about it: https://github.com/zeit/next.js/blob/master/errors/css-npm.md
Can you please help how to fix this?
Thanks.

**Comment by enerlink** [comment]
Maybe in _app.js
import 'perfect-scrollbar/css/perfect-scrollbar.css';

**Comment by lunatik-210** [comment]
that is still the case, nextjs docs provides the following description for it
https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by woothu** [comment]
Does this problem still occur in version 3?

**Comment by dkprog** [comment]
I'm still having exactly the same issue. Any ideas of how to workaround it?

**Comment by miguelguadarrama** [comment]
same here, issue still present on "@coreui/react": "^3.2.3"

**Comment by PaulBGD** [comment]
Is there any update on this? Really really want to use this library.

**Comment by swaraj27** [comment]
I am facin same issue while importing AppAside from @Coreui/react
import { AppAside } from "@coreui/react"; 

please give some solution.

**Comment by mankutila** [comment]
This is still an issue
