### ISSUE TITLE
Error in importing

### ISSUE THREAD

**Issue by vpn1997** [coreui/coreui-react#11]
`import  { DefaultLayout }   from '@coreui/react';` this gives me 
` React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.` error.

**Comment by xidedix** [comment]
You cannot import import { DefaultLayout } from '@coreui/react'; since it is placed in src/containers
