### ISSUE TITLE
react-router-dom Switch component not woking.

### ISSUE THREAD

**Issue by Daornit** [coreui/coreui-react#111]
I recently downloaded your react-admin project but when i goto the localhost:3000/login it changes to localhost:3000/login#/dashboard. It renders DefaultLayout component not a LoginPage. Any help would be greate.
![Screenshot from 2020-03-24 13-20-18](https://user-images.githubusercontent.com/34941714/77390948-6a2b3e00-6dd2-11ea-9cd4-1e348ead3f6f.png)

**Comment by balanka** [comment]
i faced similar issue, as i tried to add authentication to the admin dashboard

**Comment by shawndewet** [comment]
See [issue 116](https://github.com/coreui/coreui-react/issues/116) and the closing comment I left.  Replace `HashRouter` with `BrowserRouter` in the `App.js` file.  Might be worth trying in your scenarios?

**Comment by woothu** [comment]
This is not related to the template but to `react-router-dom`
