### ISSUE TITLE
Add Typescript definitions for v3

### ISSUE THREAD

**Issue by jcapogna** [coreui/coreui-react#112]
I'm starting to use v3 beta.1 and noticing that it lacks Typescript definitions. It would be great to have these going forward as most of my projects are Typescript these days.

**Comment by jakobjp** [comment]
@jcapogna how/where did you find the core-react v3 beta?

**Comment by jcapogna** [comment]
@jakobjp I pay for CoreUI pro. I got the update about beta3 via my Gumroad purchase a week or so ago.

**Comment by xidedix** [comment]
@jcapogna please update to @coreui/react `3.0.0-beta.3`
