### ISSUE TITLE
Breadcrumbs for Home page is not displaying.

### ISSUE THREAD

**Issue by chandanchhajer** [coreui/coreui-react#113]
Breadcrumbs for All routes are displaying as Home / <PageName> but for Home page itself (main url) is not displaying.
```
const routes = [
  {
    path: "/",
    exact: true,
    name: "Home",
    component: Dashboard,
  },
  {
    path: "/dashboard",
    name: "Dashboard",
    component: Dashboard,
  }
]
```
Expected Breadcrumb as:
Home
Home / Dashboard

But Result as:
_nothing_
Home / Dashboard

Can anyone help me if know the solution?

**Comment by xidedix** [comment]
@chandanchhajer 
what about 
```js
const routes = [
  { path: '/', exact: true, name: 'Home' },
  { path: '/dashboard', name: 'Dashboard', component: Dashboard },
]
```
and in `App.js`

**Comment by chandanchhajer** [comment]
Is there any other solution?

Also how I set routes for Page404?

**Comment by chandanchhajer** [comment]
> @chandanchhajer
> what about
> 
> ```js
> const routes = [
>   { path: '/', exact: true, name: 'Home' },
>   { path: '/dashboard', name: 'Dashboard', component: Dashboard },
> ]
> ```
> 
> and in `App.js`
> 
> ```js-jsx
> ...
> <Route path="/" name="Home" render={props => <DefaultLayout {...props}/>} />
> ...
> ```
> 
> there is also in `src\containers\DefaultLayout\DefaultLayout.js`:
> 
> ```js-jsx
> ...
> <Redirect from="/" to="/dashboard" />
> ...
> ```

Is there any other solution?
Also how I set routes for Page404?

**Comment by xidedix** [comment]
https://github.com/coreui/coreui-free-react-admin-template/blob/master/src/App.js
