### ISSUE TITLE
main scrolling below header nav

### ISSUE THREAD

**Issue by ybizeul** [coreui/coreui-react#117]
Currently it looks like `<main>` like in :

```
<body class="app">
    <div id="root">
        <header class="app-header"> <-- ...scrolling under this
           ...
        </header>
        <div class="app-body">
            <div class="sidebar">
            </div>
            <main class="main"> <-- This...
            </main>
            <div class="sidebar">
            </div>
        </div>
</body>
```

Has a content that passes under the NavBar.

This is usually not an issue, except when you try to set <a name> anchors, in that case, clicking the link put the anchor right under the NavBar.

Am I doing something wrong ?

**Comment by woothu** [comment]
When it comes to template components (sidebar, header, etc.) they have been reworked fixing a lot of bugs in v3. We are sorry but we are not fixing edge cases in v2.
