### ISSUE TITLE
Coreui-react v2 Documentation

### ISSUE THREAD

**Issue by dragonhelios** [coreui/coreui-react#119]
Hi, 

New to using coreui and trying to implement it on a new hobby project. When looking at the documentation at https://coreui.io/react/docs it seems to be only v3 documentation and using the v2 documentation link on the coreui.io/react webpage takes you to the bootstrap v2 documentation. 

Is there coreui-react v2 specific documentation or is the bootstrap documentation the relevant documentation (or the more likely am I just being thick)?

Kind regards

**Comment by woothu** [comment]
When it comes to v2 the most relevant docs are: https://coreui.io/docs/2.1/getting-started/introduction/ + bootstrap docs

We highly recommend switching to v3 as it is currently developed
