### ISSUE TITLE
CModal: Accessibility to CFade element for keyboard navigation.

### ISSUE THREAD

**Issue by Letrab** [coreui/coreui-react#120]
Since https://github.com/coreui/coreui-react/commit/55ceeef186fbe3f487d750e0e347728aa717e330#diff-07f95b801cc5ec6103efae43878229d4 the `keyboard` prop is removed.

It would be nice to be able to pass custom properties to the CFade element to be able to set custom `onKeyUp` handlers. E.g. in the already existing `transitionProps`.

**Comment by woothu** [comment]
Attributes are passed to `modal-content`. https://github.com/coreui/coreui-react/blob/master/src/modal/CModal.js

It is intended to limit CFade functionality in purpose for simplifying API and component comprehension.

I have successfully tun the following solution:
```       
<CModal 
    show={modal} 
    onClose={setModal}
    onKeyUp={() => console.log('test')}
    tabIndex="0"
>
```

**Comment by Letrab** [comment]
Thanks for your reply!

Found this as well, but it is only hit when either, in my case, the "x" (close button), next or previous button has focus.
Not when just clicked in the modal, not when clicked outside of the modal.... Which is a pity...
