### ISSUE TITLE
error when using v2.5.8 with redux

### ISSUE THREAD

**Issue by essencient** [coreui/coreui-react#121]
I am getting the following warning from react. sessionLive is a redux state assigned to props by mapStateToProps. The issue appears to be in 'react-perfect-scrollbar'. I have the latest version 1.5.8 installed. 

index.js:1 Warning: React does not recognize the `sessionLive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `sessionlive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ScrollBar)
    in ScrollBar (created by AppSidebarNav2)
    in AppSidebarNav2 (at DefaultLayout.js:185)
    in div (created by AppSidebar)
    in ClickOutComponent (created by AppSidebar)
    in AppSidebar (at DefaultLayout.js:182)
    in div (at DefaultLayout.js:181)
    in div (at DefaultLayout.js:176)
    in Elements (at DefaultLayout.js:175)
    in DefaultLayout (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at App.js:24)
    in Switch (at App.js:17)
    in Router (created by HashRouter)
    in HashRouter (at App.js:16)
    in App (at src/index.js:20)
    in Provider (at src/index.js:19)

**Comment by woothu** [comment]
'react-perfect-scrollbar' is external library. In version 3 we use our own scrollbar solution, moreover redux is integrated in template out of the box.
