### ISSUE TITLE
Example of how to use progressbar during a fetch operation?

### ISSUE THREAD

**Issue by frippe75** [coreui/coreui-react#126]
Hi,

Another newbie question. And sorry in advance but I googled it and only find ways to solve by installing other progressbars.
Do I have to use webworkers to get a background task to update the progressbar during the fetch?
The length of fetch is really unkown but I will guestimate it to around 3 sec.

Much appreciated!
/F

**Comment by woothu** [comment]
How could you show the progress of a task if you don't know the current state of the task? :P
---
For guestimation:

you can change `value` prop of CProgress dynamically

On fetch start: set interval (setInterval js function) increasing `value` by 3 every 100ms

On fetch end: reset interval and set CProgress value to `100`
