### ISSUE TITLE
Table Filter doesn't work with calculated columns

### ISSUE THREAD

**Issue by isalo** [coreui/coreui-react#129]
Table filter doesn't work if column value is calculated base on other columns

```
  <CDataTable
     items={publishers}
     fields={fields}
     scopedSlots={{
            name: (item) => (
              <td>{`${item.lastName} ${item.firstName}`}</td>
            ),
  }}/>
```
Do you have any other options how to make filter work with calculated columns?

**Comment by woothu** [comment]
The table is filtered by content passed in `items` prop. You can map `publishers` variable, it would look something like:

```
const mappedPublishers = publishers.map(publisher => {...publisher, name: publisher.lastName + ' ' publisher.firstName})
```
