### ISSUE TITLE
Migrate from V1 to V2

### ISSUE THREAD

**Issue by zianzhangzz** [coreui/coreui-react#13]
My group purchased the product around February. The current version we are at is V1.8.14. Is there any easy migrating guidelines to V2? Thanks :)

**Comment by JamesSingleton** [comment]
@zianzhangzz I am not sure exactly what needs to be updated exactly? This is just an npm library and you should be able to just update to the newest version without a problem. They did come out with a v2 version for the dashboard itself [here](https://github.com/coreui/coreui-free-react-admin-template) if that is what you mean. But as far as migrating / updating you should be able to just do `npm outdated` and then `npm update` to update to the latest version.

**Comment by NickFoden** [comment]
Hi @JamesSingleton can you clarify. They are 2 unrelated repos? If you are on V1, you can update the dependencies, but you can't change to be on the [one you link ](https://github.com/coreui/coreui-free-react-admin-template) is that correct?
