### ISSUE TITLE
How to use custom icons in side nav?

### ISSUE THREAD

**Issue by sri-vathsa** [coreui/coreui-react#135]
Currently the icons and elements in the side bar are defined as follows
```
{
    _tag: "CSidebarNavItem",
    name: "Typography",
    to: "/theme/typography",
    icon: "cil-pencil",
  }
```
in the `_nav.js` file

I want to use a custom icon by importing 
Ex:

```
import { IoIosCloudUpload } from "react-icons/io";

{
    _tag: "CSidebarNavItem",
    name: "Typography",
    to: "/theme/typography",
    icon:<IoIosCloudUpload />,
  }
```
is there a way to do this?

**Comment by woothu** [comment]
This is possible since `3.1.0` version

**Comment by sri-vathsa** [comment]
@woothu  Can you point me out to how this works? Cause I couldn't get this to work.. 
This is the error I get when I try the above 
```
Warning: Invalid values for props `$$typeof`, `type` on <svg> tag. Either remove them from the element, or pass a string or number value to keep them in the DOM. For details, see https://fb.me/react-attribute-behavior
 ```

My `package.json`
```
    "@coreui/coreui": "^3.2.2",
    "@coreui/icons-react": "^1.0.1",
    "@coreui/react": "^3.0.3",
```

**Comment by woothu** [comment]
have you run the update? lookup what version of @coreui/react do you have in `package-lock.json`

**Comment by sri-vathsa** [comment]
Yes, I've updated the packages.
Here's the version in my `package-lock.json`
```
"@coreui/react": {
      "version": "3.2.1",
```

**Comment by woothu** [comment]
Are you sure the issue is with `CSidebarNavItem`, not `CSidebarNavDropdown`? (the second one have not received this fix yet)

**Comment by sri-vathsa** [comment]
@woothu 
This is my current code

```
 <CSidebarNav>
        <CCreateElement
          items={navigation} />
```
and navigation is an array of objects like this
```
{
    _tag: "CSidebarNavItem",
    name: "Typography",
    to: "/theme/typography",
    icon:<IoIosCloudUpload />,
  }
```

**Comment by sri-vathsa** [comment]
I tried changing to other coreui icons too even that is not working
```
  {
    _tag: "CSidebarNavItem",
    name: "Teams",
    to: "/teams",
    icon: "cib-server-fault",
  },
```
gives me this
![Screenshot from 2020-07-31 17-09-13](https://user-images.githubusercontent.com/53426607/89031678-97739400-d350-11ea-9126-1a9640fc3b4c.png)

**Comment by woothu** [comment]
It works: https://codesandbox.io/s/react-csidebar-example-icon-nkbu5?file=/src/Sidebar.js

**Comment by sri-vathsa** [comment]
Not sure why but deleting node_modules and npm install did the trick.. Thanks :D
