### ISSUE TITLE
Breadcrumb: The Breadcrumb has an extra backslash

### ISSUE THREAD

**Issue by hegdemohan** [coreui/coreui-react#136]
The breadcrumb has an extra backslash when the route has a paramater in it.For example,
`{ path: '/content/edit/:id', exact: true, name: "Edit Content", component: contentEdit},`
![breadcrumb_new](https://user-images.githubusercontent.com/39328940/89403751-1aae3480-d719-11ea-8fd2-90a4b3a4f9a5.PNG)

**Comment by woothu** [comment]
This issue is resolved in the `3.2.0` version by e4d743da43a51584ddf34a54746b9bd9208df44e.
