### ISSUE TITLE
Don´t render icons

### ISSUE THREAD

**Issue by tavorazo** [coreui/coreui-react#139]
we have the premium react version.

Reading the documentation, we tried to render icons from https://icons.coreui.io/icons/ but it doesn't work.

The premium version doesn't have the icons?

`<CIcon name="cilArrowThickToRight" size="1xl"/>`

or

`<CIcon name="cil-folder-open" size="1xl"/>`

**Comment by woothu** [comment]
Icons must be imported globally to use them without imports (calling by `name` prop) 

Example of global registration: https://github.com/coreui/coreui-free-react-admin-template/blob/master/src/index.js (icons object should contain all needed icons)
