### ISSUE TITLE
CDataTable - Added custom filter datepicker using columnFilterSlot - but not working

### ISSUE THREAD

**Issue by saravananrajagopal** [coreui/coreui-react#142]
Can you please give example for columnFilterSlot  and how it works

columnFilterSlot = {{
                  scheduled_date:(
                      <DatePicker
                              name="scheduled_date"
                              className="form-control form-control-sm"
                              dateFormat="eeee, do LLLL yyyy"
                              selected={startDate}
                              onChange={date => {setStartDate(date); }}
                              minDate={new Date()}
                              filterDate={isWeekday}
                              maxDate={addWeeks(new Date(), 5)}
                              showDisabledMonthNavigation
                              popperPlacement="bottom"
                              popperModifiers={{
                                flip: {
                                  behavior: ["bottom"], // don't allow it to flip to be above
                                },
                              }}
                            />
                    )
                  
                }}

**Comment by woothu** [comment]
Here is a working example:
https://codesandbox.io/s/react-cdatatable-date-range-example-coijv?file=/src/Table.js
