### ISSUE TITLE
CoreUI Pro 2.x love demo

### ISSUE THREAD

**Issue by preetham1290** [coreui/coreui-react#143]
I was looking to buy pro version of 2.x and I could not find any live demo page. 
I want to know if dark and light mode comes with mixins or do we have switch between 2 css. I want it similar to 3.x as am using it with scss in angular code. 
If available please share.

**Comment by woothu** [comment]
Main live previews are on version 2:
https://coreui.io/angular/demo/#/dashboard
https://coreui.io/angular/demo/dark/#/dashboard

In version 3 you switch between two css, in version 3 it is switchable by one CSS class

**Comment by preetham1290** [comment]
Thank you for your response. 
Cab we customize free version by our self to support switchable by one CSS class by writing our own logic? And use it for SaaS products?

**Comment by woothu** [comment]
The dark mode is available only in the PRO version. After purchase customization for your case should be possible (although I think it would be optimal just to migrate to v3)

**Comment by preetham1290** [comment]
Sorry i meant can we customize our self with our own logic from free version? like a derivative of free version

**Comment by woothu** [comment]
The free version is licensed by MIT, so you are free to do anything you want with it :)

**Comment by preetham1290** [comment]
Thanks a lot for your help.
