### ISSUE TITLE
TypeScript integration breaks icons

### ISSUE THREAD

**Issue by sundaramgupta** [coreui/coreui-react#144]
Integrating TypeScript breaks the way icons work in CoreUI.

index.tsx
```
Property 'icons' does not exist on type 'typeof React'.  TS2339

    13 | import { Provider } from "react-redux";
    14 | 
  > 15 | React.icons = icons;
```

Is there a workaround to fix this?

**Comment by WillyRamirez** [comment]
@woothu I have a fresh install and this issue still exists for me. The commit that fixes #133 does not seem to solve this.
