### ISSUE TITLE
Sidebar Minimized missing scroll on sidebar items

### ISSUE THREAD

**Issue by AdnanBoota** [coreui/coreui-react#145]
Hello,

Thanks for the wonderful library, it has been very helpful in our projects.

We just realized that, with the latest of version of coreui-react, when the sidebar is minimized with property `<CSidebar minimize={true} >` the scrollbar is not available. It is not possible to see all the items when the sidebar is minimized, as there is no scroll option available.

Could you please activate the scrollbar for the `<CSidebar minimize={true} >` ?

Thanks a lot, attached is the image for your reference.

![image](https://user-images.githubusercontent.com/14972616/91316344-ffcf5d00-e7b8-11ea-9261-b9f19724b33c.png)

**Comment by woothu** [comment]
We are aware of this issue, but there is no good solution for this bug at this moment (it is limited by CSS)

**Comment by major697** [comment]
any resolve this problem ?
