### ISSUE TITLE
How to improve the documentation?

### ISSUE THREAD

**Issue by Downsidelama** [coreui/coreui-react#148]
I am using CoreUI's admin template and I wanted to create a CDataTable with my custom filtering because I am using server-side pagination.  
However, it is not mentioned in the documentation, that you need to pass in columnFilter={{external: true}} to use your own implementation.  
Do you have a repository with the documentation so that I could create a pull request with enhancements or do you keep it private?

**Comment by Morrious** [comment]
@Downsidelama I know this is old, but can you detail how you use an external columnFilter? I am trying to make a smarter filter so I can filter _out_ values with syntax like "-value".

**Comment by Morrious** [comment]
For those interested, I created my own custom filtering for my CDataTable. I don't know that CoreUI has a CDataTable in version 4, this is using coreui-react 3.2.3.

My CDataTable is within my Class Component render function. I have to bind my `onColumnFilterChange ` function to my component in my constructor, so it can access my state:
```javascript
this.onColumnFilterChange = this.onColumnFilterChange.bind(this);
```

In my state, I have `items`, `filteredItems`, and my column `fields`. The default value of `filteredItems` is null so I can remove the custom filter functionality by not setting the filter function.
```javascript
this.state = {
  items: [],
  filteredItems: null,
  fields: null,
};
```

My CDataTable takes these variables in like this within render():
```javascript
let { fields, items, filteredItems } = this.state;
<CDataTable
  fields={fields}
  items={filteredItems ?? items}
  columnFilter={{ external: true }}
  onColumnFilterChange={this.onColumnFilterChange}
/>
```

Lastly, my custom function looks like this. I haven't actually changed any of the default filtering logic yet, but you could change the filter logic to match your needs in this function:
```javascript
onColumnFilterChange(columnFilterState) {
  const { fields, items } = this.state;
  const itemsDataColumns = fields.map((f) => f.key);

  let filteredItems = items;
  Object.entries(columnFilterState).forEach(([key, value]) => {
    const columnFilter = String(value).toLowerCase();
    if (columnFilter && itemsDataColumns.includes(key)) {
      filteredItems = filteredItems.filter((item) => {
        return String(item[key]).toLowerCase().includes(columnFilter);
      });
    }
  });
  this.setState({ filteredItems });
}
```
