### ISSUE TITLE
AppLayout module not found warning

### ISSUE THREAD

**Issue by joostfarla** [coreui/coreui-react#15]
First of all, thanks for this awesome project!
I'm getting this warning when importing this project as ES module.

```
WARNING in ./node_modules/@coreui/react/es/index.js
32:0-35 "export 'default' (reexported as 'AppLayout') was not found in './Shared'
```

It looks like the `Shared` module is missing a default export.

**Comment by krgaurav1992** [comment]
Facing the same issue. Please try to resolve this

**Comment by xidedix** [comment]
hi @joostfarla , @krgaurav1992 
I am trying to reproduce, but without success.
Here are my steps:
````bash
git clone https://github.com/coreui/coreui-free-react-admin-template.git
cd coreui-free-react-admin-template/
npm i
npm start
````

**Comment by krgaurav1992** [comment]
Just created a pull request with the required changes. Please review.

**Comment by xidedix** [comment]
please include steps to reproduce the issue, so we can verify it

**Comment by krgaurav1992** [comment]
The issue is encountered when importing modules directly from "coreui-react". I am using it in my existing project, not in `coreui-free-react-admin-template`

**Comment by sanymochi** [comment]
I'm getting this warning when try to import coreui js: 
./node_modules/@coreui/coreui/dist/js/coreui.min.js
Module not found: Can't resolve 'perfect-scrollbar' in '/media/oem/76B0B2F5B0B2BAC7/Sunny/dg2/project/DG2/SourceCode/Web/dg2/node_modules/@coreui/coreui/dist/js'
