### ISSUE TITLE
Attributes in navigation bar do not work.

### ISSUE THREAD

**Issue by sagardewani-db** [coreui/coreui-react#153]
Attributes provided in the navbar module doesn't work. It is also spread inaccurately in core modules/ source code. Please fix it.
`const nav = [{
      _tag: 'CSidebarNavItem',
      name: 'Logout',
      attributes: { onClick: (e) => { performLogout() } },
    }];`

`<CCreateElement 
   items={nav}  
   components={{
     CSidebarNavDivider,
     CSidebarNavDropdown,
     CSidebarNavItem,
     CSidebarNavTitle
  }}/>`

Output:
`<a href="#" class="c-sidebar-nav-link" attributes="[object Object]" tabindex="0">Logout</a>`

**Comment by Greegles** [comment]
Try const nav = [{ _tag: 'CSidebarNavItem', name: 'Logout', onClick: () => console.log('test') }];
