### ISSUE TITLE
CModal component disregards className prop

### ISSUE THREAD

**Issue by MikeDabrowski** [coreui/coreui-react#159]
CModal component disregards `className` prop passed to it. According to the documentation it should use that prop and add it to its other classes. In the code I also do not see this prop being used.

https://github.com/coreui/coreui-react/blob/903003fc046e2046b18d76117fc074fa44c2a99b/src/modal/CModal.js#L66-L69

Also https://github.com/coreui/coreui-react/blob/master/CONTRIBUTING.md is 404.

**Comment by xidedix** [comment]
Issue has been fixed in v3.3.3
