### ISSUE TITLE
CSidebar throws error when using Show property

### ISSUE THREAD

**Issue by V0ren** [coreui/coreui-react#166]
Hey. I am using the Free React Template and running into a issue with `CSidebar`. When using the 'Show' property it will throw an error whenever I auto complete in any input field on the page. 

My setup: 
```HTML
<CSidebar
   show={showSidebar}
   onShowChange={onShowChanged}
>
```

`onShowChanged` toggles the values of showSidebar. 

The error produced: 
```
Uncaught TypeError: Cannot read property 'includes' of undefined
    at HTMLDocument.onKeydown (CSidebar.js:74)
```

And the CoreUI code that it breaks on: 
```javascript
 var onKeydown = function onKeydown(e) {
    e.key.includes('Esc') && isAutoclosable() && closeSidebar();
  };
```

This error does not appear if I do not use the show property on the CSideBar but I like to make use of that.

**Comment by yauheniivashkevich** [comment]
For me, this issue is reproducible when selecting an autocomplete value from the input
