### ISSUE TITLE
To locate the bad setState() call inside `CDataTable`

### ISSUE THREAD

**Issue by UgurKacak** [coreui/coreui-react#168]
Hello, I am updating state in the function that I caught a page change on the table. However, when I change the page, I get the error.
Error:
`index.js:1 Warning: Cannot update a component (`JobTable`) while rendering a different component (`CDataTable`). To locate the bad setState() call inside `CDataTable`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

JobTable is component that I'm trying to update state after "onPageChange".

CDataTable props:
`<CDataTable
					.
                                        .
					onPageChange={pageChangeHandler}
                                        .
                                        .`

pageChangeHandler function : 
`const pageChangeHandler = (pageNumber) => {
		setCurrentPage(pageNumber);
		setSelectAllChecked(false);
	};`

**Comment by UgurKacak** [comment]
I created a custom datatable from the library and added my own function and the problem was solved.

**Comment by dzakiafif** [comment]
@UgurKacak @hdlinh1808 hi. did u solved about this?

**Comment by UgurKacak** [comment]
Hello sorry for late response.

It's not the right way, but I added all the code of CoreUI datatable as a component to my own project and then made changes where the error was found.

**Comment by dzakiafif** [comment]
@UgurKacak hmm can u show me sample how you made changes it? cause i think to handle prop onpagechange we can use modified props pagination using own style pagination and using onactivepagechange.

**Comment by UgurKacak** [comment]
Sorry, it's an enterprise private repository of one of my customers and I don't have access rights.

**Comment by dzakiafif** [comment]
> Sorry, it's an enterprise private repository of one of my customers and I don't have access rights.

thank you
