### ISSUE TITLE
CDataTable sorter use in some selected fields not on all fields

### ISSUE THREAD

**Issue by barakjobs** [coreui/coreui-react#169]
I am using CDataTable and want to use sorter only for some selected fields/columns, not for all the columns.
Can you please help me on this.

**Comment by Gabriel-Mariano** [comment]
Você poder passar assim:

{ key:"intervalo", label:"Intervalo", _style: { width: "25%" }, sorter:true },
{ key:"redirecionamento", label:"Direcionamento", _style: { width: "30%" }, sorter:false },
{ key:"status", label:"Status", _style: { width: "30%" }, sorter:true },

se passar o sorter como false no seus campos, ele não irá aparecer.
