### ISSUE TITLE
`CDropdownDivider` and `CDropdownHeader` aren't defined in the index.d.ts file 

### ISSUE THREAD

**Issue by Ygilany** [coreui/coreui-react#170]
When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, etc...): irrelevant - MacOS
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser): irrelevant - Chrome
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
![image](https://user-images.githubusercontent.com/11262007/102548554-d64c8100-4088-11eb-81c7-f6937d7e3799.png)

`@coreui/react` definitions file doesn't export `<CDropdownDivider>` nor `<CDropdownHeader>

**Comment by xidedix** [comment]
thanks @Ygilany fixed with v3.4.1
