### ISSUE TITLE
2.0.1 breaks app: Module not found (coreui-utilities)

### ISSUE THREAD

**Issue by zaweb** [coreui/coreui-react#18]
After updating to 2.0.1, my React app no longer builds. I get this error:
Module not found: Can't resolve '@coreui/coreui/dist/js/coreui-utilities in Dashboard.js
I verified that coreui-utilities is not present. 
I tried removing node_modules and reinstalling, but that did not help. 
When I revert back to 2.0.0 the problem goes away.

**Comment by xidedix** [comment]
Hi @zaweb
What’s your version of CoreUI template?

**Comment by zaweb** [comment]
coreui-pro 2.0.2

**Comment by xidedix** [comment]
import path for pro version is `@coreui/coreui-pro/dist/js/coreui-utilities`

**Comment by zaweb** [comment]
Thanks! Had to update the path in a few places (Dashboard, MainPage, Themes/Colors), but updating the path fixed the issue. Thanks again!
