### ISSUE TITLE
CDataTable Change striped backgroundcolor, and change thead background color

### ISSUE THREAD

**Issue by skybreathe** [coreui/coreui-react#182]
how can i customize style of CDataTables, i need to style striped table and table head, i've read the documentation about CDataTable React, but i can't find how to custom these

**Comment by csleary** [comment]
I'm sure you sorted this out a long time ago, but just for future reference, there's a striped boolean prop. But if you have any other rows within a collapse component, this may not be sufficient, in which case you'll need to set a custom `:nth-of-type(fn)` class.
