### ISSUE TITLE
There is no way to change input placeholder on DataTable filter?

### ISSUE THREAD

**Issue by GuilhermeAmado** [coreui/coreui-react#186]
I'm developing an app that's not in english, so I need to change "Filter: type string..." that comes by default on the filter input of the DataTable component.

**Comment by xidedix** [comment]
@GuilhermeAmado  what about: 
```jsx
<CDataTable
  tableFilter={{label: 'Label', placeholder: 'your placeholder '}}
  ...
```

**Comment by GuilhermeAmado** [comment]
> @GuilhermeAmado what about:
> 
> ```js
> <CDataTable
>   tableFilter={{label: 'Label', placeholder: 'your placeholder '}}
>   ...
> ```

Yes, this works... The documentation could be a lot better. Where I was supposed to find this?
