### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by AliBdeir** [coreui/coreui-react#190]
Is there a guide on migrating to coreui 4? There are a couple of breaking changes, and a list of these breaking changes in the doc would be a huge help.

**Comment by mrholek** [comment]
Next week I'm going to release migration guide

**Comment by AliBdeir** [comment]
Any update on the migration guide?

**Comment by jaimouest** [comment]
I'm interested too

**Comment by mrholek** [comment]
Please check following links

https://coreui.io/react/docs/4.0/migration/v4/
https://coreui.io/docs/4.0/migration/

**Comment by msmanek** [comment]
hey @mrholek -> thanks for taking the time to make a migration guide. However, it seems like it's not 100% complete. Certain components are not given a migration path. Ex:
`CFade` -> https://coreui.io/react/docs/migration/v4/#cfade
`CFormGroup` -> https://coreui.io/react/docs/migration/v4/#cformgroup

I suppose I can track down the PRs that removed them, but I was wondering if there were any docs I could consult to make an easy migration path from v3 to v4?
