### ISSUE TITLE
Invalid CDropdownMenu type

### ISSUE THREAD

**Issue by thepixelmonk** [coreui/coreui-react#192]
Unable to compile stock CDropdownMenu examples

```
  Type '{ children: Element; }' is missing the following properties from type 'CDropdownMenuProps': outOfBoundaries, scheduleUpdate  TS2739

      45 |                   <CDropdown variant="nav-item">
      46 |                     <CDropdownToggle color="secondary">{this.props.staff.firstName} {this.props.staff.lastName}</CDropdownToggle>
    > 47 |                     <CDropdownMenu>
         |                      ^
      48 |                       <CDropdownItem href="#" onClick={(e:any) => { e.preventDefault();this.props.logOut() }}>Logout</CDropdownItem>
      49 |                     </CDropdownMenu>
      50 |                   </CDropdown>
```

**Comment by WilixLead** [comment]
Change to 
`<CDropdownMenu outOfBoundaries scheduleUpdate={() => {}}>` 
it help me for compile, but react rise warnings like 
`Warning: React does not recognize the `outOfBoundaries` prop on a DOM element`

**Comment by thangchung** [comment]
We have got the same issue, just wonder how can we fix this bug? or just work around it because after using spread to ignore these `outOfBoundaries`, `scheduleUpdate` props, then the CDropDownMenu wasn't working anymore. 

Is anyone help to fix it? Thank you.
