### ISSUE TITLE
CDataTable sorting and filtering not being applied correctly?

### ISSUE THREAD

**Issue by quantropi-cmckenzie** [coreui/coreui-react#193]
Hi. I wouldn't post this without first scouring the net and your issues first. I know it sounds like a common user error but its possible I simply don't understand how the filter/sort work after reading the docs.

OS: Ubuntu 20.04 LTS
Browser: Chrome 87

Basically I'm going crazy trying to get column filtering and sorting working with this table data. Only the 1st column ('date') actually sorts (the sort icon is missing from the other columns). The column filtering only works with the 1st column ('date') and it doesn't work at all with the others. If I set the `onColumnFilterChange` I can clearly see the filter criteria and its correct (e.g. { name: "8", date: "21"}, BUT if I insert a break point in my getData() function (which returns the data array) it only fires when the "date" column it updated. It's like the other column filter fields haven't been hooked up to the filter event.

Finally, when trying to filter the "date" column for the actual displayed date (e.g. 2021/05/22) it'll filter out. It looks like / is not permitted or supported. Can someone confirm? I can change my date format, but before I do that I'd like the sort/filter support to work correctly.

Any help is greatly appreciated. Thanks.

Here's my CDataTable usage:

```
             <CDataTable
              items={getData()}
              fields={[
                { key: "date", label: "Date", _style: { width: "20%" } },
                { key: "name", label: "Name", _style: { width: "20%" } },
                { key: "bytes", label: "Amount", _style: { width: "20%" } },
                { key: "bytes_round", label: "Amount (formated)", _style: { width: "20%" } },
              ]}
              size="sm"
              sorter
              hover
              itemsPerPageSelect
              itemsPerPage={20}
              pagination
              columnFilter
              sortable
              onColumnFilterChange={(v) => { console.log(v) }}
              onFilteredItemsChange={setCurrentItems}

              scopedSlots={{
                date: (item) => (
                  <td>{moment(item.date).format(date_format)}</td>
                ),
                name: (item) => (
                  <td>{listItems.devices[item.device_id].name}</td>
                ),
                bytes: (item) => (
                  <td>{item.consumed_bytes}</td>
                ),
                bytes_round: (item) => (
                  <td>{FormatBytes(item.consumed_bytes)}</td>
                )
              }}
            />
```

Here's a small clip of the array returned from getData():

```
[
   {id: 391, date: "2021-05-31T00:00:00.000Z", device_id: 1, consumed_bytes: "1142107000"},
   {id: 392, date: "2021-05-31T00:00:00.000Z", device_id: 2, consumed_bytes: "1165289000"}
]
```

**Comment by xidedix** [comment]
@quantropi-cmckenzie 
Look at your arrays of items returned from getData(). There are no fields named `name`, `bytes`, `bytes_round`. 
On the `fields` object prop, the `key` defines column name equal to the item key (required). 

What you need is to transform raw items data into your desired structure, sth like:

```js
// not tested
const rawData = getData();

const items = rawData.map((item) => {
  return {
    ...item, 
    name: listItems.devices[item.device_id].name,
    bytes: item.consumed_bytes,
    bytes_round: FormatBytes(item.consumed_bytes)
  }
})
```

Btw, in this case, you can probably remove slots for name, bytes, and bytes_round.

**Comment by quantropi-cmckenzie** [comment]
Ah! I guess the scopedSlots don't count. That makes sense based on something in another table I observed. Thanks so much. The React docs need to be updated. CDataTable is a major component and a lot is missing from how to use it correctly. Thanks again.

**Comment by Omargn** [comment]
Any chance you can share the final code to this? I stil can't figure it out.
