### ISSUE TITLE
CPopover HTML content with events do not fire inside

### ISSUE THREAD

**Issue by quantropi-cmckenzie** [coreui/coreui-react#201]
OS: Ubuntu 20.04
Browser: Chrome 87.04280.66
React: 17.0.1

Ok, this one is really frustrating. I think I'll have to write a custom component or try Tippy directly. When using CPopover with some HTML content containing a button, the onClick event will not fire. It's being blocked by something or the event is replaced. It's impossible to tell from browser debug tools what the hell is attached to an element, so I can't tell what's going on.

The disappointing part is the Coreui docs and Pro Admin sample only showing basic CPopover content. The docs mention 'title' as the header attribute, but its 'header' and there's no React sample with a button inside the popover to demo that it actually works.

Here's a clip:

```
                  <CPopover
                    header={`Test Header`}
                    content={<button onClick={(e) => alert('test')}>Test</button>}
                    interactive={true}
                    trigger="click">
                    <CButton color="success">Test</CButton>
                  </CPopover>
```

Button rendered inside the popover content will not fire the onclick event. Very frustrating.

**Comment by quantropi-cmckenzie** [comment]
Yup. Switched to Tippy react and it works fine. There's something in CPopover that you're doing which messes up the element events attached during rendering.

**Comment by mrholek** [comment]
Do you use @coreui/react v3 or v4?

**Comment by quantropi-cmckenzie** [comment]
v3, v4 is/was too new. We'll have to look at migrating to v4 eventually.
