### ISSUE TITLE
[CDataTable] Filter nested objects / fields

### ISSUE THREAD

**Issue by Erumshammim** [coreui/coreui-react#205]
I am trying to filter nested field(productName) how can i do that? @mrholek  @xidedix @thomasjohn  please help me with this issue.
![Capture11](https://user-images.githubusercontent.com/37778174/126034962-6148affc-50e5-4f02-8c76-0b29b4b21f7e.PNG)

![image_2021-07-17_155606](https://user-images.githubusercontent.com/37778174/126034807-219fdfbf-7250-40b1-ae27-d3f42f9cfbc9.png)

**Comment by csleary** [comment]
With non-string/number fields I think a custom filter is your only option. So you would have to use the `onColumnFilterChange` function to use the returned current filter value to only keep list items that passes your custom filter condition.

**Comment by Erumshammim** [comment]
> With non-string/number fields I think a custom filter is your only option. So you would have to use the `onColumnFilterChange` function to use the returned current filter value to only keep list items that passes your custom filter condition.

@csleary could you please share example code?

**Comment by Morrious** [comment]
For those interested, I created my own custom filtering for my CDataTable. I don't know that CoreUI has a CDataTable in version 4, this is using coreui-react 3.2.3.

My CDataTable is within my Class Component render function. I have to bind my `onColumnFilterChange ` function to my component in my constructor, so it can access my state:
```javascript
this.onColumnFilterChange = this.onColumnFilterChange.bind(this);
```

In my state, I have `items`, `filteredItems`, and my column `fields`. The default value of `filteredItems` is null so I can remove the custom filter functionality by not setting the filter function.
```javascript
this.state = {
  items: [],
  filteredItems: null,
  fields: null,
};
```

My CDataTable takes these variables in like this within render():
```javascript
let { fields, items, filteredItems } = this.state;
<CDataTable
  fields={fields}
  items={filteredItems ?? items}
  columnFilter={{ external: true }}
  onColumnFilterChange={this.onColumnFilterChange}
/>
```

Lastly, my custom function looks like this. I haven't actually changed any of the default filtering logic yet, but you could change the filter logic to match your needs in this function:
```javascript
onColumnFilterChange(columnFilterState) {
  const { fields, items } = this.state;
  const itemsDataColumns = fields.map((f) => f.key);

  let filteredItems = items;
  Object.entries(columnFilterState).forEach(([key, value]) => {
    const columnFilter = String(value).toLowerCase();
    if (columnFilter && itemsDataColumns.includes(key)) {
      filteredItems = filteredItems.filter((item) => {
        return String(item[key]).toLowerCase().includes(columnFilter);
      });
    }
  });
  this.setState({ filteredItems });
}
```
