### ISSUE TITLE
beta-4 CFormCheck Name Prop does not exist

### ISSUE THREAD

**Issue by NickisyourFan** [coreui/coreui-react#207]
Hello! Loving the new version so far. Great work!

I am having trouble with the CFormCheck component -- Typescript is saying that "name" does not exist as a property of this element. 

I have checked out the coreui version 4 docs, as well as the github react-admin-template usage and this repo itself to see that ya'll are using the name property... but I am still stuck. 

My package.json coreui deps include:

```
  "@coreui/coreui": "4.0.1",
  "@coreui/icons": "^2.0.1",
  "@coreui/icons-react": "^1.1.0",
  "@coreui/react": "4.0.0-beta.4",
  "@coreui/utils": "^1.3.1",
  "core-js": "^3.16.1",
```

Thanks for any help!

**Comment by mrholek** [comment]
hi in beta.4 we split this component to `CFormInput` and `CFormTextarea`

**Comment by NickisyourFan** [comment]
Wow crazy quick response. 

Hmm. I might be a bit confused - I checked out this, which uses beta4 and still has CFormCheck for a Radio input. 
https://github.com/coreui/coreui-free-react-admin-template/blob/v4/src/views/components/forms/checks-radios/ChecksRadios.js

I saw that you have switched CFormControl out for those, and I have done that with success. The problem I am having is with the radio input --- Is this also getting switched out? It seems like this was new as well. 

```
                  <CFormCheck
                    id="type"
                    name="type"
                    type="radio"
                    label="Service"
                    onChange={() => form.handleChange("service")}
                  />
```

**Comment by NickisyourFan** [comment]
No worries! Thanks so much. If you need more information please let me know - I am happy to help.

**Comment by mrholek** [comment]
I know where is a problem, in our interface we extend `HTMLAttributes` instead of `InputHTMLAttributes`

**Comment by NickisyourFan** [comment]
Yup! That worked! Thanks!
