### ISSUE TITLE
CImage and CTableDataCell -- Incorrect Types 

### ISSUE THREAD

**Issue by NickisyourFan** [coreui/coreui-react#208]
Hello! 

It looks like the `src` element is not included in the `CImage` element released in v4.0.0. I changed the type definition from HTMLAttributes to ImgHTMLAttributes, and it seems to work. I think this might be a bug. 

In addition, I can't access the colspan prop on CTableDataCell, but do not know the typing to fix. 

Great improvements over the last few weeks.

**Comment by mrholek** [comment]
I fixed those interfaces in the next release.

**Comment by mrholek** [comment]
Fixed in v4.0.0-rc.1
