### ISSUE TITLE
Just downloaded free CoreUI template to test it out and it doesn’t even work

### ISSUE THREAD

**Issue by originpulses** [coreui/coreui-react#209]
I just downloaded latest release and npm installed and npm start it shows this.

![Screen Shot 2021-09-14 at 11 20 26 am](https://user-images.githubusercontent.com/64883936/133178859-c37c204d-bb74-402c-bbf0-f3208fd1fc46.png)

**Comment by jaewon1022** [comment]
same as me

**Comment by mrholek** [comment]
Hi, please download v4 https://github.com/coreui/coreui-free-react-admin-template/archive/refs/heads/v4.zip
