### ISSUE TITLE
[React] CFormLabelProps doesn't accept htmlFor

### ISSUE THREAD

**Issue by lucagalbu** [coreui/coreui-react#214]
Before opening:

- Operating system and version (Windows)
- Browser and version (Chrome, Firefox)

CFormLabelProps  is defined in [this way](https://github.com/coreui/coreui-react/blob/e6fb371f26b8cb9450f0d7cc941efcea8006d475/packages/coreui-react/src/components/form/CFormLabel.tsx#L5):

```TS
export interface CFormLabelProps extends HTMLAttributes
```

However, `HTMLAttributes` doesn't include the correct props (e.g. it is missing the prop `htmlFor`). I think the correct version is:

```TS
export interface CFormLabelProps extends AllHTMLAttributes
```

**Comment by mrholek** [comment]
Fixed in v4.0.2
