### ISSUE TITLE
On SmartTable, the cleaner doesn't empty the column inputs

### ISSUE THREAD

**Issue by Chinimala** [coreui/coreui-react#217]
All of this can be tested on the official doc : https://coreui.io/react/docs/4.0/components/smart-table/#basic-usage . I encountered the bug in my own use case.

On SmartTable, clicking on the general filter cleaner doesn't empty the column inputs, even though it cleans the column filter values (so all lines come back in the results).

(The search itself is weird in the doc, I don't understand the logic behind. For example, searching for more than one letter in the name column doesn't find any result. Fortunately I don't have this problem in my case.)

**Comment by mrholek** [comment]
Fixed in v4.0.2

**Comment by Chinimala** [comment]
It works, thank you
