### ISSUE TITLE
On SmartTable, can't align pagination at middle or end

### ISSUE THREAD

**Issue by Chinimala** [coreui/coreui-react#218]
On SmartTable, we can't align the default smart pagination at middle or end, with paginationProps={{align: 'end'}} for example.

Suggested solution : replace className="col-auto" with className="col" in the div surrounding CSmartPagination, line 495 of CSmartTable.tsx.

**Comment by mrholek** [comment]
Thanks, I will fix it in the next release.

**Comment by mrholek** [comment]
Fixed in v4.0.1
