### ISSUE TITLE
[React] CBreadcrumbRouter no longer available in coreui/react 4.x

### ISSUE THREAD

**Issue by amplexus** [coreui/coreui-react#221]
I upgraded my coreui/react project to 4.x but now I find that CBreadcrumbRouter is no longer defined:

`Attempted import error: 'CBreadcrumbRouter' is not exported from '@coreui/react'. `

This worked previously in @coreui/react 3.2.2. Can you provide guidance on what (if any) replaces this, or if/when it will be ported to 4.x?

Thanks,

**Comment by mrholek** [comment]
This component is deprecated because requires an external router component. We moved this react router implementation directly to the template, you can check it here - https://github.com/coreui/coreui-free-react-admin-template/blob/main/src/components/AppBreadcrumb.js

**Comment by amplexus** [comment]
Awesome. Thanks!
