### ISSUE TITLE
On SmartTable, the sorterValue doesn't work since 4.0.1

### ISSUE THREAD

**Issue by Chinimala** [coreui/coreui-react#224]
On the SmartTable component, the sorterValue props doesn't work anymore since v4.0.1.

I don't have access to the react-pro repo so I don't know the diffs, but by looking at source code, I have a suspect : it would be because there is
`previousSorterValue.current = sorterValue`
at line 114 on CSmartTable.tsx, then it is checked at line 329 :
`JSON.stringify(previousSorterValue.current) !== JSON.stringify(sorterValue) && setSorterState({ ...sorterValue })`
As the previousSorterValue was already updated, setSorterState would not be called.

**Comment by mrholek** [comment]
Fixed in v4.0.2

**Comment by Chinimala** [comment]
It works, thank you
