### ISSUE TITLE
CSmartTable columnSorter.resetable is ignored

### ISSUE THREAD

**Issue by lucagalbu** [coreui/coreui-react#225]
Adding the option `columnSorter` to CSmartTable, I correctly get a table whose columns can be sorted. However, based on the documentation setting `columnSorter.resetable` makes sorter have three states: ascending, descending and null. I expect  that setting it to `false` would make the sorter have only two states: ascending and descending.

However this is not the case. The field `sorter` seems to be ignored by CSmartTable.
``` TS
import React from "react";
import {
  CSmartTable,
} from "@coreui/react-pro";

export default function Table() {
  const columns = [
    {
      key: "name",
      _style: { width: "40%" },
      _props: { color: "primary", className: "fw-semibold" }
    },
    "registered",
  ];

  const usersData = [
    {id: 0, name: "John Doe", registered: "2018/01/01" },
    {id: 1, name: "Samppa Nori", registered: "2018/01/01"},
    {id: 2, name: "Estavan Lykos", registered: "2018/02/01"}
  ];

  return (
    <CSmartTable
      columns={columns}
      columnSorter = {{resetable: false}}
      items={usersData}
    />
  );
}
```

**Comment by mrholek** [comment]
Fixed in v4.0.2
