### ISSUE TITLE
How can i use "useRef" in CInput componente? 

### ISSUE THREAD

**Issue by lorranNogueira** [coreui/coreui-react#227]
How can i use "useRef" in CInput componente?

`const refPeso = useRef(null);

<CInput
      maxLength={5}
      type="text"
      name="peso"
      id="peso"
      placeholder="Kg"
      onChange={(e) => setpeso(e.target.value)}
      ref={refPeso}
    />`

The property current of refPeso ever is null.

**Comment by mrholek** [comment]
Ref.current is null because the ref is not set till after the function returns and the content is rendered.

Try to use useEffect hook

`
useEffect(() => {
    console.log(refPeso.current);
  }, [refPeso])
`
