### ISSUE TITLE
CFormSelect dropdown style doesn't comply with the dark style

### ISSUE THREAD

**Issue by lucagalbu** [coreui/coreui-react#228]
When switching to the dark theme, the background color of CFormSelect dropdown stays white. Since the text turns white because of the dark style, this makes it impossible to read the options.

As an example, we can just use the online admin template: https://coreui.io/react/demo/4.0/dark/#/forms/select
Try to open any select input and you will see that the options are invisible.

**Comment by mrholek** [comment]
@lucagalbu do you have this problem in Firefox?

**Comment by lucagalbu** [comment]
I have this problem in all the browsers I tried on Windows 10:
1) Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)
2) Firefox 94.0.2 (64-bit)
3) Edge Version 96.0.1054.34 (Offizielles Build) (64-Bit)

**Comment by Getterac7** [comment]
I'm having this issue as well. `<CFormSelect>` doesn't show options with the dark theme, except for the one that is highlighted.
![image](https://user-images.githubusercontent.com/3600185/155821110-480ed28c-8949-43bb-89a7-d3eaad2b9f94.png)

**Comment by osd-barry** [comment]
Same here. Any workaround?
