### ISSUE TITLE
CSmartTable onSelectedItemsChange not working properly

### ISSUE THREAD

**Issue by aviran3369** [coreui/coreui-react#233]
Hi,

I use these versions:
 - @coreui/coreui-pro: 4.0.4
 - @coreui/react-pro: 4.0.0

The onSelectedItemsChange event of CSmartTable not firing in these cases:
 - When a single row is checked and I uncheck it
 - Where I check\uncheck the top checkbox to toggle all items (In this case it will be nice to be able to know if the checkbox is checked\unchecked\indeterminate)

Thanks

**Comment by mrholek** [comment]
Please update:

@coreui/coreui-pro: to 4.1
@coreui/react-pro: 4.1
