### ISSUE TITLE
CSmartTable scopedColumns not working in TypeScript

### ISSUE THREAD

**Issue by pcholewa** [coreui/coreui-react#236]
Hi,

I use these versions:

@coreui/coreui-pro: 4.1.0
@coreui/react-pro: 4.1.0

Not working properly when creating simple CSmartTable with props scopedColumns, example component:

`const TableExample = () => {
  const items: Item[] = ([
    {
      _id: 0,
      _props: {},
      _selected: false,
      name: 'Example name'
    }
  ])

  return <CSmartTable
    items={items}
    columns={[
      {
        key: 'name',
        label: 'Name'
      }
    ]}
    scopedColumns={{
      name: () => <span>test</span>
    }}
  />
}`

**Comment by mrholek** [comment]
Try this

`        name: (item) => (
          <td>{item.name}</td>
        ),`

**Comment by Getterac7** [comment]
> ` name: (item) => ( <td>{item.name}</td> ),`

I'm having the same issue and this doesn't work because:

> `Object literal may only specify known properties, and 'name' does not exist in type 'ScopedColumns'.`

**Comment by mrholek** [comment]
Please update @coreui/react-pro to 4.1.1

**Comment by Getterac7** [comment]
Going from @coreui/react-pro 4.1.0 to 4.1.1 fixed it. Thanks!
