### ISSUE TITLE
custom size in modal

### ISSUE THREAD

**Issue by dzakiafif** [coreui/coreui-react#244]
i see in CModal for props size strict in ['', 'sm', 'lg', 'xl'] but i want to add custom size for CModal. is it possible to custom it?

**Comment by KPeschke** [comment]
@dzakiafif 
You can use "className".

Example:
```
<CModal
    className="my-custom-modal-size"
    ...
>
    Your modal content
</CModal>
```

In your stylesheet something like:
```
.my-custom-modal-size .modal-dialog {
  max-width: 25vw !important;
}
```

**Comment by dzakiafif** [comment]
> @dzakiafif You can use "className".
> 
> Example:
> 
> ```
> <CModal
>     className="my-custom-modal-size"
>     ...
> >
>     Your modal content
> </CModal>
> ```
> 
> In your stylesheet something like:
> 
> ```
> .my-custom-modal-size .modal-dialog {
>   max-width: 25vw !important;
> }
> ```

ahhh i see. so, the logic if when we add some custom size in props size just ternary like size={!['', 'sm', 'lg', 'xl'].includes(customsize) ? '' : size} and then we must add custom css too right?
