### ISSUE TITLE
CSmartTable CoreUI 4.1.2 pro custom column filters.

### ISSUE THREAD

**Issue by cossminuu** [coreui/coreui-react#254]
Hello,

Not really a feature request because maybe already exists but doesn't make sense to post it in the "issues" section.

Can someone tell me please if it's possible to add custom column filters?

![Screenshot 2022-02-10 083305](https://user-images.githubusercontent.com/47316223/153369912-cb07bc49-7e2f-4656-96c4-353aa3301b40.png)

Instead of the default one (search input), to add something custom like a "date picker" or a dropdown. 

If I'm not wrong, it was possible in a previous version. 

Thank you.

**Comment by mrholek** [comment]
@cossminuu we're going to add more filter options in future releases. We will add select, multi-select, and this new component https://coreui.io/react/docs/4.1/forms/date-range-picker/

**Comment by mrholek** [comment]
@cossminuu I will do my best to release it in the first half of next month.

**Comment by cossminuu** [comment]
Ok. Thank you @mrholek

**Comment by MatteoBuffo** [comment]
@mrholek please take in account also a time picker and date-time picker. Thanks!

**Comment by cossminuu** [comment]
@mrholek Any news about this? thanks

**Comment by MatteoBuffo** [comment]
Hi @mrholek! Now that the new filters have been added in version 4.1.2, how do you make use of them in a `CSmartTable`?

**Comment by MatteoBuffo** [comment]
@cossminuu not yet, @mrholek is currently working on it and he will make it available in the next release.

**Comment by sergiofcpaulino** [comment]
Any update on this issue and when it will be resolved?

**Comment by mrholek** [comment]
@sergiofcpaulino It's almost done, I have to update the documentation, and check it one more time. I'm going to release new version next week.

**Comment by mrholek** [comment]
Added in v4.4.0 - https://coreui.io/react/docs/components/smart-table/#custom-filters

**Comment by karlobencic** [comment]
Seems like custom filters don't work in combination with external data sources, any plans on implementing or fixing that in the near future?

**Comment by mudassir1996** [comment]
I used dropdown for custom filter with external data source like this
```
{
        key: 'type_asset',
        label: 'Type',
        filter: (value, change) => {
            const dropdownOptions = props.assetTypeTaxonomy

            return h(CFormSelect, {
                size: 'sm',
                onChange: (selected) => {
                    change(selected.target.value)
                },
                options: [
                    { value: '', label: 'All' },
                    ...dropdownOptions.map((element) => {
                        return {
                            value: element.term_id,
                            label: element.name,
                        }
                    })
                ],
            })
        },
    },
```
