### ISSUE TITLE
How Can I change the Dark theme to light

### ISSUE THREAD

**Issue by muhammadadnan97** [coreui/coreui-react#256]
I have Purchase React Admin Panel v4 Pro version which comes with Default theme. Can you Please guide me how can I change that to Light theme

**Comment by mrholek** [comment]
@muhammadadnan97 please go to `src/components/AppSidebar.js` add add  `colorScheme="light"` to `<CSidebar>` component

**Comment by muhammadadnan97** [comment]
@mrholek  Thanks it's work now. but looks like scrollbar style is missing still.

![image](https://user-images.githubusercontent.com/17389828/153959403-704f1669-82e8-4e3a-b304-353d7db840fd.png)

**Comment by mrholek** [comment]
@muhammadadnan97 what is your browser and OS, I will check it.

**Comment by muhammadadnan97** [comment]
Google Chrome, Windows 11

**Comment by muhammadadnan97** [comment]
Google Chrome, Windows 11
