### ISSUE TITLE
Incorrect documentation for CoreUI Modal component

### ISSUE THREAD

**Issue by sandercm** [coreui/coreui-react#262]
Hello,

This is not really a bug report because it is not related to the code directly but to the documentation. 

In the documentation for the Modal component we get the example 
![image](https://user-images.githubusercontent.com/11708237/159471575-7654b1cb-ffcf-4447-aca8-49c0783e3265.png)

this uses `onClose()` inside the <CModal> tag but when you look at the interface for the <CModal> component you can see that it actually expects you to use onDismiss. This isn't obvious if you use the Close Button in the example but can cause confusion when the behavior suddenly doesn't work properly when using the cross in the Header. 

![image](https://user-images.githubusercontent.com/11708237/159471807-f4250631-b41e-4ffe-89e5-cfacedd5ab6d.png)

**Comment by mrholek** [comment]
Please update the version of @coreui/react
