### ISSUE TITLE
Module '"@coreui/react-pro"' has no exported member 'CDatePicker'.

### ISSUE THREAD

**Issue by paerck25** [coreui/coreui-react#264]
- Operating system and version : MacBook Pro (13-inch, M1, 2020)  Monterey 12.2.1  
- Browser and version : Chrome

sorry, im not good at english

i need date-picker

i installed  @coreui/react-pro@next

![스크린샷 2022-03-23 오전 11 05 43](https://user-images.githubusercontent.com/59303527/159608509-a9dde5e2-77f2-4213-9d60-b40e446a7513.png)

**Comment by mrholek** [comment]
Fixed in v4.2.0

**Comment by reaxvip** [comment]
> Fixed in v4.2.0

No, it's not :(

**Comment by RohitGhosh7703** [comment]
> Fixed in v4.2.0

Hey its 2024 and its still not fixed.
