### ISSUE TITLE
How to handle onClick on CDropdownItem  coreUI 4.2 pro

### ISSUE THREAD

**Issue by dinhtrung90** [coreui/coreui-react#266]
Hi guys,
 I am using coreUI 4.2 Pro, but i'm getting a stuck at onClick on CDropdownItem
this is my code 
`<CDropdownItem  href="#" onClick={handleLogout}>
          <CIcon icon={cilLockLocked} className="me-2" />
          Logout
        </CDropdownItem>`

it seems like that not working in this version, so could u give me some advice for this case?

**Comment by mrholek** [comment]
@dinhtrung90 I will fix it in the next release.

**Comment by mrholek** [comment]
Fixed in v4.2.0
