### ISSUE TITLE
Documentation of react components?

### ISSUE THREAD

**Issue by bhakta0007** [coreui/coreui-react#27]
Hello,

can you please point to the documentation of the ReactJs components of coreUI. I looked around (https://coreui.io/docs) but there is no mention of the react components.

**Comment by caktoy** [comment]
I also need the documentation for the reactjs version.
I check in the documentation page, but there is only common javascript version.

**Comment by AlexStansfield** [comment]
Yeah would be handy, we paid for the Pro version, but have to look at both the standard docs and the source code of the example admin template in order to figure out how to do it. Would be good to have proper documentation.

**Comment by joao-cesar** [comment]
Hi. Is there an update on it?

**Comment by xidedix** [comment]
At the start, we thought the template was self-explanatory. Apparently it's not, and it lacks proper docs.
We are working hard to bring the new CoreUI v3 with full-blooded documentation.

In the meanwhile: 
- for CoreUI v2 for React components see: https://github.com/coreui/coreui-react/blob/master/src/README.md
- for Reactstrap: https://reactstrap.github.io/components/

Best regards.

**Comment by Jakkc** [comment]
Any update on this? I still can't seem to find anything useful in the obvious places

**Comment by woothu** [comment]
Version 3 of the library is much better documented: https://coreui.io/react/docs/

**Comment by cyberhafid** [comment]
with the version "@coreui/react": "^2.5.1", it's ok

**Comment by xidedix** [comment]
##### CoreUI v3
- https://coreui.io/react/docs/

##### CoreUI v2
- https://github.com/coreui/coreui-react/blob/v2/src/README.md

**Comment by casamia918** [comment]
Hey guys. I have a question.

Can I get more detailed document when buying pro version? Or the document is same with the above link page? 

I've read document page of above link. But they seems to have too short explanation for use this library.
