### ISSUE TITLE
Property 'src' does not exist on CCardImage props

### ISSUE THREAD

**Issue by miguel-fresh** [coreui/coreui-react#278]
I'm using the `CCardImage` inside a `CCard` just like this: 
![image](https://user-images.githubusercontent.com/101909267/165814319-6fc61368-3e7a-4505-8abe-c7f27be76a09.png)

And I'm having this error: 

```
ERROR in ./src/components/ProductBox/ProductBox.tsx 64:39-42
TS2322: Type '{ orientation: "top"; src: string; }' is not assignable to type 'IntrinsicAttributes & CCardImageProps & RefAttributes<HTMLOrSVGElement | HTMLOrSVGImageElement>'.
  Property 'src' does not exist on type 'IntrinsicAttributes & CCardImageProps & RefAttributes<HTMLOrSVGElement | HTMLOrSVGImageElement>'.
    62 |         </div>
    63 |
  > 64 |         <CCardImage orientation="top" src={productImages[0].path} />
       |                                       ^^^
    65 |         <ProductInput
    66 |           idPrefix={reference}
    67 |           value={reference}

```

I monkey-patched it adding the `src: string` prop to the `CCardImageProps` interface and it started working fine, so I guess it's just a TS typo?

## **Using:**
- OS: Windows 10
- Browser: Chromium rendering engine (with Electron)

**Comment by nickisyourfan** [comment]
I also have confirmed this issue with @coreui/react version 4.2.0.

**Comment by mrholek** [comment]
@miguel-fresh @nickisyourfan will be fixed in next release

**Comment by mrholek** [comment]
Fixed
