### ISSUE TITLE
React 18 and  latest version of @coreui/react

### ISSUE THREAD

**Issue by malishahi** [coreui/coreui-react#283]
I am trying to install the latest version of @coreui/react, but I faced the following error. Is the latest version of @coreui/react compatible with React 18?

Thanks.
npm install @coreui/react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: status-app-client@0.0.1
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17" from @coreui/react@4.2.1
npm ERR! node_modules/@coreui/react
npm ERR!   @coreui/react@"*" from the root project

**Comment by mrholek** [comment]
@malishahi we're working on it.

**Comment by mrholek** [comment]
Added in v4.2.2

**Comment by qazwsxedccsqzse** [comment]
npm install @coreui/react --force
