### ISSUE TITLE
CChart tooltips not showing like the demo

### ISSUE THREAD

**Issue by thuhoai179** [coreui/coreui-react#284]
Chart tooltip is not showing as the [Demo](https://coreui.io/react/docs/components/chart/#bar-chart). Instead it shows **under** the chart when a data point is hovered.

![image](https://user-images.githubusercontent.com/86884893/170446313-4888cbe3-6fa2-42e3-a0ff-3d86c754918d.png)

This is the demo: ![image](https://user-images.githubusercontent.com/86884893/170446244-baa8d555-7e5a-482e-aac2-0e8dbe4fe799.png)

My code (copied from the [Docs ](https://coreui.io/react/docs/components/chart/#cchart)):
```
<CChart
  type="bar"
  data={{
    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
    datasets: [
      {
        label: 'GitHub Commits',
        backgroundColor: '#f87979',
        data: [40, 20, 12, 39, 10, 40, 39, 80, 40],
      },
    ],
  }}
/>
```
Is the a dependency/additional lib that I'm missing? Looking forward for some help.
I'm using version 2.0.0, when I update to version 2.0.3 this bug still exist.

**Comment by 21jake** [comment]
Same issue here. Couldn't figure out what's missing.

**Comment by sonck201** [comment]
I got the same issue and couldn't figure out
