### ISSUE TITLE
Controlled Popover

### ISSUE THREAD

**Issue by MatteoBuffo** [coreui/coreui-react#301]
Hi! My goal is to have a controlled Popover, i.e. an external event can control the visibility of the Popover.

This is my code:

```
const [popoverVisible, setPopoverVisible] = useState(false);

<CButton
  onClick={() => setPopoverVisible(!popoverVisible)}
>Toggle Popover visibility</CButton>

<CPopover
  content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus."
  placement="top"
  visible={popoverVisible}
>
  <CButton color="secondary" onClick={null}>Popover on top</CButton>
</CPopover>
```

but it doesn't work: the popover appears/disappears only when I click the button inside of it.

Any tip/suggestion on how to achieve my goal?

Thanks.

**Comment by mrholek** [comment]
@MatteoBuffo done :) It will be available in the next release, next week.
