### ISSUE TITLE
CSmart Table Header

### ISSUE THREAD

**Issue by jgeagea** [coreui/coreui-react#306]
Hello,

Is it possible to show an example of how to add a header to columns in CSmart Table?

I am trying this way:

let returnedColumns = [

            {
                label: "test"

            },
            {
                label: "name",

                columns: [
                    {
                        label: "first_name"
                    },
                    {
                        label: "last_name"
                    }
                ]
            }

        ];

**Comment by xidedix** [comment]
prop `columns:  string|Column[]` 

|prop|type||notes
|---|---|---|---  
| key | string | *required* | Column name equal to the item key.
| label | string |  | Visible caption of column (auto-generated if not specified).
| _classes | string/array/object || Adds classes to all cells in a column.
| _style | string/array/object || Adds styles to the column header (useful for defining widths).
| sorter | boolean || Disables sorting of the column when set to `false`.
| filter | boolean || Removes filter from column header when set to `false`.

```js
let items = [
  { first_name: 'John', last_name: 'Doe' },
  { first_name: 'Arthur', last_name:  'Dent' },
  { first_name: 'Tricia', last_name: 'McMillan' },
]

let columns = [
  { key: 'first_name' },
  { key: 'last_name' },
]
```
or 
```js
let columns = ['first_name', 'last_name']

```

gives:

First Name|Last Name
---|---
John|Doe
Arthur|Dent
Tricia|McMillan

**Comment by jgeagea** [comment]
Thank you for your reply!

Is it possible to have a header column as "name" which combines 2 columns (first_name and last_name) ?

**Comment by xidedix** [comment]
@jgeagea, thanks for the clarification!
We're considering implementing column header groups.
