### ISSUE TITLE
Visual Studio Start Up

### ISSUE THREAD

**Issue by fhlee74** [coreui/coreui-react#31]
I have just bought the Pro version.  Is there any quick start Visual Studio GitHub project that I can download and quickly understand (and apply) CoreUI?  I am having a hard time identifying and downloading all the packages and components and npm packages. I still haven't have any success getting CoreUI to run on Visual Studio. Am begining to think this is a bad decision. It will be very useful if you have a git project I can just download and see how it works. Thanks

**Comment by fhlee74** [comment]
Apparently, there is one already at http://github.com/mrholek/CoreUI-Net

**Comment by xidedix** [comment]
see also:
http://www.coderepo.blog/posts/building-elegant-applications-aspnet-core-mvc-2.1-coreui-2-bootstrap-4/
