### ISSUE TITLE
react select component not able to validate required property

### ISSUE THREAD

**Issue by veenapan** [coreui/coreui-react#313]
I have added required property for CFormSelect inside CForm but on submit button, form is not validating dropdown

`<CFormSelect 
                className="mb-2" 
                aria-label="Small select example" 
                onChange={handleAddFormChange} 
                value={formData.selectedoption} 
                required
                name="selectedoption">
                <option>Select Option</option>
                <option value="W">W</option>
                <option value="DS">DS</option>
                <option value="ML">ML</option>
                <option value="B">B</option>
              </CFormSelect> `

**Comment by snkhan120** [comment]
I have a same issue

**Comment by mrholek** [comment]
@snkhan120 please try to add first option with `value=""` 

ex. `<option value="">Choose...</option>`
