### ISSUE TITLE
Error while creating build

### ISSUE THREAD

**Issue by MatteoBuffo** [coreui/coreui-react#317]
Hello.

Please take a look at the screenshot: since I updated to the latest version of this library, I've been stumbling upon an error while launching this build command.
![build_error](https://user-images.githubusercontent.com/56068232/184926546-8c7c80fe-35c0-42de-b70d-172e3ac8e425.png)

Thanks in advance.

**Comment by DiegoArrieta** [comment]
same issue +1

**Comment by DiegoArrieta** [comment]
> Hello.
> 
> Please take a look at the screenshot: since I updated to the latest version of this library, I've been stumbling upon an error while launching this build command. ![build_error](https://user-images.githubusercontent.com/56068232/184926546-8c7c80fe-35c0-42de-b70d-172e3ac8e425.png)
> 
> Thanks in advance.

@MatteoBuffo 
solved, adding this to the package.json

`
"resolutions": {
    "postcss-custom-properties": "^9.1.1"
  }
`

**Comment by MatteoBuffo** [comment]
Woah, it worked! Thank you a lot @DiegoArrieta!

**Comment by xidedix** [comment]
cannot reproduce on `@coreui/coreui-free-react-admin-template@4.4.0 `
