### ISSUE TITLE
CTimePicker cleaner doesn't fire onTimeChange event

### ISSUE THREAD

**Issue by karls4** [coreui/coreui-react#320]
CTimePicker cleanerdoesn't fire onTimeChange event. Should fire the onTimeChange event so that the state can be updated with the new value.

**Comment by mrholek** [comment]
@karls4 will be fixed in the next release

**Comment by mrholek** [comment]
Please update @coreui/react-pro to v4.7.2.

Using `onTimeChange` event you will get `null` when clear.
