### ISSUE TITLE
Failed Prop Type In CoreUI React Navbar COffcanvas, 

### ISSUE THREAD

**Issue by suhailroushan13** [coreui/coreui-react#322]
- Operating System Info

![ssfef](https://user-images.githubusercontent.com/58624583/192741660-bed3daff-dc58-4c71-93d9-cad9e3056ee9.png)

- In Core UI React Navbar COffcanvas, 
- React Prop Type is Failed placement of down 

- Browser Version (Using Brave Browser)

![ssrgrrgr](https://user-images.githubusercontent.com/58624583/192742814-44bf0ed1-958f-4022-8a11-4fcf8783cb6a.png)

![image](https://user-images.githubusercontent.com/58624583/192739463-ea8d1081-8834-4362-a561-6d7521526cc6.png)

- This is a Core UI React Navbar COffcanvas,
![imag2222](https://user-images.githubusercontent.com/58624583/192740944-c1d28534-bb93-42bc-89a3-eda0dbfbed49.png)

- Using placement type down in Component 
![ssssssss](https://user-images.githubusercontent.com/58624583/192740734-040d8b40-35b6-412f-8288-13f36451f213.png)

**Comment by mrholek** [comment]
@suhailroushan13 offcanvas doesn't support `placement="down"`, you have to use `placement="bottom"`

**Comment by suhailroushan13** [comment]
> @suhailroushan13 offcanvas doesn't support `placement="down"`, you have to use `placement="bottom"`

If i am using it, it's showing a new design type of NavBar can we use it like a new design ??
