### ISSUE TITLE
CModal `keyboard` doesn't respect state value

### ISSUE THREAD

**Issue by Jared-Dev** [coreui/coreui-react#325]
Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
  - macOS
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
  -  Chrome
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
  - This is required for a paid product?

I have the pro version of the react library. I've added a piece of state to track whether or not a form within a modal is "dirty" or not.

I'm trying to prevent closing the modal by hitting escape based on that state. The form is for adding a user and I don't want them to accidentally close the modal and lose any state they may have changed.

I've confirmed that this works when passing the value statically, but it isn't respected when the value of the state changes. I also attempted to look at the various events that are exposed, but since there isn't an event that is passed (which contains how it was triggered i.e. escape/clicking the backdrop) I can't even code around this.

**Comment by mrholek** [comment]
@Jared-Dev backdrop property is not reactive at this moment, but I will change it in the next release. It should be ready by the end of next week.
