### ISSUE TITLE
I found a not working button in Coreui-React.js site

### ISSUE THREAD

**Issue by darkpsinight** [coreui/coreui-react#326]
Hi, in [this page (modal components)](https://coreui.io/react/docs/components/modal/#fullscreen-modal) the button "Full screen below md" doesn't work at all when clicking on it, the button does no action, it's broken.
What i'm expecting is upon cliking on "Full screen below md" blue button, i should get a modal sized md.
This issue is tested in private Window with all extensions disabled and still getting a broken button.
Consider fixing it asap.

**Comment by xidedix** [comment]
@darkpsinight thanks for pointing this out. 
There is a typo at the third line of code example. It ought to be:
```js
const [visibleMd, setVisibleMd] = useState(false)
```

In this case the modal component should cover user viewport **below** `md` breakpoint (`768px`)
