### ISSUE TITLE
Validations provide no feedback when floatingLabel is set

### ISSUE THREAD

**Issue by T3rm1** [coreui/coreui-react#327]
```
<CFormInput id="username" name="username" floatingLabel="Username"
  placeholder="Username" feedbackInvalid="Does not show up" feedback="Does not show up" invalid aria-describedby="username"/>
```
When `floatingLabel` is set, no feedback shows up. Neither valid feedback nor invalid feedback.

**Comment by mrholek** [comment]
@T3rm1 at this moment floating labels don't support those elements, but I will check how to improve it.

**Comment by mrholek** [comment]
@T3rm1 Probably yes, but I have to check it.

**Comment by mrholek** [comment]
Added in v4.5.0
