### ISSUE TITLE
How To Enable Dark Theme

### ISSUE THREAD

**Issue by caktoy** [coreui/coreui-react#33]
I was buy CoreUI Pro edition, in website said it contains dark theme, I want to use it, how I do it? Is there just change some configuration or something else to use dark theme in react version?

**Comment by xidedix** [comment]
hi @caktoy 
Please look at `src/scss/style.scss` in template source and find the description how to switch to the dark theme in comments of this file.

**Comment by caktoy** [comment]
Oke thanks, I get it.

**Comment by learnlapp** [comment]
@xidedix 

thanks for the reply. I uncommented 

`@import "@coreui/coreui-pro/scss/themes/dark/coreui-dark";`

but i don't see the themes/dark directory when in 

[https://ibb.co/fKd5Cq](url)

**Comment by denu5** [comment]
@learnlapp man, I can help you and everyone else reading this!

you are missing the tilde in the import statement:

`
@import "~@coreui/coreui/scss/themes/dark/coreui-dark";
`

**Comment by tezqa** [comment]
Hi everyone,

I uncommented `@import "~@coreui/coreui-pro/scss/themes/dark/coreui-dark.scss";` but still no dark theme. Any idea?

**Comment by icemancml** [comment]
Hi everyone, I bought tht pro angular UI, I am using the alpha 3.0. I don't see the same namespace so I changed:
@import "~@coreui/coreui-pro/scss/coreui";  TO :  @import "~@coreui/coreui-pro/scss/themes/dark/theme";

But is not working,

**Comment by Fornori** [comment]
document.body.classList.add('dark-theme')
