### ISSUE TITLE
Customize the theme colors

### ISSUE THREAD

**Issue by makkahwi** [coreui/coreui-react#333]
In V.4.2.0 free version

Still very unclear on how to customize the theme colors.

As I get it, I should add following lines to _custom.scss. But it's not work, if someone could type down exactly how to do so.

`@import "../../node_modules/@coreui/coreui/scss/coreui";

$primary: #2B2B2B;
$secondary: #3F7A5E;

$theme-colors: (
  "primary": $primary,
  "secondary": $secondary
);`

**Comment by mrholek** [comment]
Your custom variables should be defined before `@import "../../node_modules/@coreui/coreui/scss/coreui";
