### ISSUE TITLE
Incorrect work of filters in CSmartTable (React)

### ISSUE THREAD

**Issue by idkroff** [coreui/coreui-react#334]
OS: Windows 11 
Browser - Opera v93.0.4585.37

When using the basic CSmartTable from Coreui Pro React v4.1.0, working with filter fields is incorrect (you can enter only 1 character at a time, after which the table component is presumably re-rendered, and it is impossible to continue entering)

Proof - https://imgur.com/a/6A3vAVN

**Comment by mrholek** [comment]
@idkroff v4.1.0 it's old version, please upgrade to the latest v4.6.1

**Comment by idkroff** [comment]
> 

When I try to download the new version, I get a message that the key is invalid. When I try to restore it, I get a message that the key is not attached to the mail. Can you give us some contacts so that we can solve this situation?
