### ISSUE TITLE
Custom popover using css

### ISSUE THREAD

**Issue by g-sharat** [coreui/coreui-react#340]
I am trying to give popover a customization but it is not working. 

in page.js
`import styles from "../../../utils/styles.module.css";`
`<CPopover
                  placement="bottom"
                  trigger="hover"
                  content="my content"
                  className={styles.custompopover}
                >
                  <CAvatar color="primary" textColor="white" className="mb-2">
                    BM
                  </CAvatar>
                </CPopover>
`
in styles.module.css
`.custompopover {
  --cui-popover-bg: #437544;
  --cui-popover-body-padding-y: 10px;
}`

I did try to change it in custom.scss

`.custompopover {
  $popover-bg: rgb(221, 10, 10) !important;
  $popover-body-padding-y: 0.1rem;
}` and in page `<CPopover
                  placement="bottom"
                  trigger="hover"
                  content="my content"
                  className="custompopover"
                >
....
`
Nothing works and popover looks transparent with just text. Any help would be appreciated

**Comment by mrholek** [comment]
@g-sharat I have to improve better className handling, because at this moment it overwrite default classes. It will be ready in the next release.

**Comment by mrholek** [comment]
@g-sharat please update @coreui/react to 4.5.1

**Comment by g-sharat** [comment]
@mrholek I have checked and it is fixed now 👍 so I am closing this issue. Thanks for the quick fix 😄
