### ISSUE TITLE
How to programmatically send toasts?

### ISSUE THREAD

**Issue by pkatta-ktc** [coreui/coreui-react#344]
We are currently using react-toastify (https://www.npmjs.com/package/react-toastify)
 
**We have this code currently:**
```
 useEffect(() => {
    if (isSuccess) {
        toast.success('You successfully executed the action');
    }
  }, [isLoading]);

```
I am not able to send a toast using CToast/CToaster, in the same line where we currently do "toast.success".  I keep getting various Typescript/React errors.  Can you please give me a code snippet to send a CToast?

**Comment by wolfgang720** [comment]
I'm also wondering how the Toasts/Toasters work.

The example in the [CoreUI React docs](https://coreui.io/react/docs/components/toast/#basic) is extremely simple and doesn't explain the function of the components and leave a lot of questions open:

- why is there a state field called 'toast'?
- why is it initialized with 0, when later a toast component is "added"? (Why is the setState function called "addToast")
- why the ref?
- what is the difference between CToast and CToaster? What is their respective purpose?
- how do i translate that example to a big page with a deeper component hierarchy? Where do I need to put what? 

Of course, one could find out with with trial and error, but honestly, what are the docs for?

**Comment by wolfgang720** [comment]
I got it working with a React context. This is not a beautiful solution, but maybe it helps someone in the future:

Set up a React context (I did it in my private layout component):
```
export const PrivateContext = React.createContext<{ addToast: Function }>({ addToast: () => {} });

const PrivateLayout = () => {
  const toaster = useRef(null);
  const [toast, setToast] = useState();
  return (
    <PrivateContext.Provider value={{ addToast: setToast }}>
      <AppSidebar />
      <div className="wrapper d-flex flex-column min-vh-100 bg-light dark:bg-transparent">
        <AppHeader />
        <div className="body flex-grow-1 px-3 page-branded-bg">
          <AppContent />
          <CToaster ref={toaster} push={toast} placement="top-end" />
        </div>
        <AppFooter />
      </div>
    </PrivateContext.Provider>
  );

export default PrivateLayout;
```

Since I always want the same style for the toast, apart from the color, I decided to go for a custom hook for easier use in components:
```
import React from 'react';
import { CToast, CToastBody, CToastHeader } from '@coreui/react-pro';
import { PrivateContext } from 'layout/PrivateLayout';
import { useContext } from 'react';

type ToastColor = 'primary' | 'secondary' | 'info' | 'success' | 'warning' | 'danger';

export default function usePrivateToast() {
  const { addToast } = useContext(PrivateContext);

  return {
    dispatchToast: (title: string, message: string, color: ToastColor = 'primary') => {
      const newToast = (
        <CToast color={color}>
          <CToastHeader closeButton className="d-flex justify-content-between">
            {title}
          </CToastHeader>
          <CToastBody>{message}</CToastBody>
        </CToast>
      );
      addToast(newToast);
    },
  };
}
```

Dispatch a toast:
```
const SomeComponent = () => {
  const { dispatchToast } = usePrivateToast();
  return (
    <CButton onClick={() => dispatchToast('toast title', 'toast message')}>Send toast</CButton>
  )
}
```

It'd be really nice if such an example (or preferrable a better one was in the docs).

**Comment by jcapogna** [comment]
@wolfgang720 I ended up basically copying your solution. It worked great. 

I'm upgrading an app from CoreUI v3 to v4 and the new CToaster API with push() was a confusing piece for me. With v3, CToaster took an array of child CToasts, so I was using Redux to manage my toasts, but this didn't make sense with the new API in v4. 

 It would be great for some version of wolfgang720's solution to be in the docs or a better solution if the CoreUI authors have one.

**Comment by mrholek** [comment]
@pkatta-ktc @wolfgang720 @jcapogna we're going to improve the toaster in v5 which should be available before the holidays, so we are open to suggestions.

**Comment by jcapogna** [comment]
@mrholek I think the toaster needs to be a global app component in most apps. The examples in the docs only show it being used within a component which is simpler to figure out how to use. I use toasts as confirmations which often happens while the user is changing routes, which means the toaster has to live higher in the component tree than the routes, which results in my toaster being global (e.g in AppLayout.tsx in your template app). 

My main suggestion would be to pick an opinionated solution for implementing a global toaster (perhaps @wolfgang720's solution) and implement that in your starter template. I have no problem with the CoreUI components not being an out-of-the-box solution as long as the starter templates provide a good implementation. A good example of this is the CoreUI breadcrumb components, where you've provided an example in the starter templates in AppBreadcrumb for integrating React Router with the CoreUI breadcrumbs.

**Comment by pkatta-ktc** [comment]
React-toastify has the best approach.  I recommend you mirror their approach.  The toast container lives at the top of the container tree.  That allows one to programmatically send toasts in a very easy and consistent manner.

**Comment by jcapogna** [comment]
Under the hood, react-toastify is probably similar to @wolfgang720's solution. 

I ended up writing a file called Toaster.tsx that looks like this:
```
import React, {ReactElement, useContext} from 'react'
import {CToast, CToastBody, CToastHeader} from '@coreui/react-pro'

export const ToasterContext = React.createContext<{ addToast: Function }>({ addToast: () => {} });

export function useToaster() {
    const { addToast } = useContext(ToasterContext);

    return {
        dispatchToast: (title: string, message: string|ReactElement) => {
            const newToast = (
                <CToast autohide={true} animation={true} delay={3000}>
                    <CToastHeader closeButton className="d-flex justify-content-between">
                        {title}
                    </CToastHeader>
                    <CToastBody>{message}</CToastBody>
                </CToast>
            );
            addToast(newToast);
        },
    };
}
```

In my AppLayout, I wrapped everything with the ToasterContext and added the CToaster.
```
const AppLayout = () => {

    const toaster = useRef(null);
    const [toast, setToast] = useState<ReactElement|undefined>(undefined);

    return (
        <ToasterContext.Provider value={{ addToast: setToast }}>
            <AppSidebar/>
            <div className="wrapper d-flex flex-column min-vh-100 bg-light dark:bg-transparent">
                <AppImpersonationHeader/>
                <AppHeader/>
                <div className="body flex-grow-1 px-3">
                    <AppContent/>
                </div>
                <AppFooter/>
            </div>
            <CToaster ref={toaster} placement="bottom-end" push={toast}/>
        </ToasterContext.Provider>
    )
}
```

Then throughout my app, I can simply create toasts by doing this:
```
const toaster = useToaster();
toaster.dispatchToast("title", "body);
```

I think the stuff I have in Toaster.tsx should probably be part of the CoreUI library. What I ended up with is pretty clean, though the react-toastify API seems little simpler still.

**Comment by jcapogna** [comment]
One thing that is nice about the CoreUI approach is that the CToast elements are very customizable as shown in the docs. If there is a way to keep that customizability while simplifying the global toaster setup like in react-toastify, that would be ideal.
