### ISSUE TITLE
CSmartTable example fails TypeScript checking

### ISSUE THREAD

**Issue by ktwbc** [coreui/coreui-react#345]
Example for external data use example on CSmartTable at  https://coreui.io/react/docs/components/smart-table/ will fail to compile in TypeScript due to schema check. Even documented in the code:

```
  /**
   * Enables default pagination. Set to true for default setup or pass an object with additional CPagination props. Default pagination will always have the computed number of pages that cannot be changed. The number of pages is generated based on the number of passed items and 'itemsPerPage' prop. If this restriction is an obstacle, you can make external CPagination instead.
   */
  pagination?: boolean
```

the directions say you can pass a boolean or an object, but the variable is only defined as boolean.  TypeScript will fail

```
322: Type '{ external: true; }' is not assignable to type 'boolean'.
     97 |       itemsPerPage={itemsPerPage}
     98 |       itemsPerPageSelect
    99 |       pagination={{
        |       ^^^^^^^^^^
    100 |         external: true
    101 |       }}
    102 |       paginationProps={{
```

**Comment by mrholek** [comment]
@ktwbc please install [4.8.0-alpha.3](https://www.npmjs.com/package/@coreui/react-pro/v/4.8.0-alpha.3)

**Comment by ktwbc** [comment]
Yes that works (and as a bonus fixed the paginator disappearing issue)!
