### ISSUE TITLE
AppAside

### ISSUE THREAD

**Issue by kelvinblade** [coreui/coreui-react#35]
I bought the pro version but the documentation doesn't tell me how to change width of AppAside and how to toggle it with a function, thanks.

**Comment by kelvinblade** [comment]
@xidedix thanks that worked

can you tell me how to toggle it with a function instead of using AppAsideToggler? Thanks

**Comment by xidedix** [comment]
@kelvinblade 
all you need is a custom function toggling `aside-menu-show` or `aside-menu-${display}-show` class like `AsideToggler` does

**Comment by kelvinblade** [comment]
@xidedix 
i am not sure how to do that in react, can you help me?

**Comment by sheethalpatila** [comment]
I have faced this issue 
  AppSidebar,
  AppSidebarHeader,
  AppSidebarNav,
  AppSidebarMinimizer,
  AppSidebarFooter,
  AppSidebarForm,
  AppFooter,
  AppHeader,
  AppBreadcrumb
  
  
  I have resolved like this 

  import {
  CSidebar,
  CSidebarHeader,
  CSidebarNav, 
  CSidebarFooter,
  CForm,
  CFooter,
  CHeader,
  CBreadcrumb,
  CSidebarBrand,
  CSidebarToggler,
} from from '@coreui/react';
