### ISSUE TITLE
CMultiselect dropdown not shown when the down icon is pressed

### ISSUE THREAD

**Issue by saba-softiez** [coreui/coreui-react#353]
Hi,
CMultiselect dropdown is not shown when the down icon is pressed. But the dropdown opens when clicked inside the text control.

**Steps to reproduce:** This is not working in the documentation itself. [https://coreui.io/react/docs/forms/multi-select/#basic-example](https://coreui.io/react/docs/forms/multi-select/#basic-example )

Thank you,
Saba

**Comment by mrholek** [comment]
Please upgrade `@coreui/coreui-pro` to v4.4.4
