### ISSUE TITLE
StrictMode breaks dropdown positioning

### ISSUE THREAD

**Issue by Lartza** [coreui/coreui-react#358]
To easily reproduce, wrap https://github.com/coreui/coreui-free-react-admin-template in StrictMode.
Navigation dropdown renders top left, behind sidebar (minimize sidebar to see it in top left). Any added dropdown also renders in a wrong position.

Windows 11
Happens on both Firefox 112 and Edge 112

**Comment by pushkar-embrill** [comment]
Need to add custom css to CDropdownMenu.
<CDropdownMenu style={{ zIndex: 100, top: "100%" }}>

**Comment by matr369** [comment]
I have the same issue, and style={{ zIndex: 100, top: "100%" }} isn't the best solution to fix that, since it isn't centered.
