### ISSUE TITLE
Dropdown not Open Proper position in localhost react Strict Mode

### ISSUE THREAD

**Issue by pushkar-embrill** [coreui/coreui-react#359]
I have Implemented a Dropdown in ReactJs project. Right now I cannot open the dropdown at the proper position in localhost strict mode. 
When I implemented it, it was working perfectly. Even it is working on the live site but not in localhost.

"@coreui/coreui": "^4.2.0",
"@coreui/react": "^4.3.0",
  
<CDropdown className="project-switch">
          <CDropdownToggle href="#" color="Primary">
            open
          </CDropdownToggle>

          <CDropdownMenu>
                <CDropdownItem>
                  name
                </CDropdownItem>
<CDropdownItem>
                  car
                </CDropdownItem>
<CDropdownItem>
                  bike
                </CDropdownItem>
          </CDropdownMenu>
        </CDropdown>

**Comment by pushkar-embrill** [comment]
After using zIndex it renders on position but still, it covers the button.
<CDropdownMenu style={{ zIndex: 100 }}>
![Screenshot from 2023-05-11 17-58-29](https://github.com/coreui/coreui-react/assets/126167600/7ae5cd50-5c92-4798-af57-79e5416b5038)

**Comment by mrholek** [comment]
Please update 

```
"@coreui/coreui": "^4.2.6",
"@coreui/react": "^4.8.0",
```

and check if problem exist.
