### ISSUE TITLE
add tooltip to sidebar nav link

### ISSUE THREAD

**Issue by agdolla** [coreui/coreui-react#36]
Is it possible to add tooltip to a sidebar nav link ?

**Comment by xidedix** [comment]
As a workaround you can add the html `title` attribute to `src/app/_nav.ts` like this:
```js
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'icon-speedometer',
    attributes: { title: 'Dashboard tooltip'}
  },
```

**Comment by kevinashworth** [comment]
The necessary syntax is actually this:

**Comment by xidedix** [comment]
@kevinashworth 
you are right for sidebar-nav `title`  element (when `title: true`) 
in this case, `title` is wrapped with `<a>` element
