### ISSUE TITLE
CFormSelect - empty option value attribute removed

### ISSUE THREAD

**Issue by sKopheK** [coreui/coreui-react#363]
System specs: Windows 11, latest Chrome
"@coreui/coreui": "^4.2.6",
"@coreui/react": "^4.5.1",

```
<CFormSelect 
  options={[
    { label: 'Please choose...', value: '' },
    { label: 'Option one', value: 'one' }
  ]}
/>
```

HTML result:

```
<select>
  <option>Please choose...</option>
  <option value='one'>Option one</option>
</select>
```

empty `value` attribute is not present causing browser to return node content when the first option is manually selected instead of empty/undefined value

expected HTML result:

```
<select>
  <option value=''>Please choose...</option>
  <option value='one'>Option one</option>
</select>
```

**Comment by mrholek** [comment]
@sKopheK i will improve it in the next release
