### ISSUE TITLE
'visible' prop not working properly in CNavGroup component

### ISSUE THREAD

**Issue by ZaidWaseem10** [coreui/coreui-react#365]
I would like to report a bug in the CoreUI-React library regarding the 'visible' prop in the CNavGroup component. Currently, when attempting to toggle the visibility of the CNavGroup by setting the 'visible' prop to either true or false, it does not reflect any change in the component's visibility.

**Comment by ahoward2** [comment]
This is a real issue. I'm considering just controlling this myself.
