### ISSUE TITLE
CModal not opening in Beta

### ISSUE THREAD

**Issue by karls4** [coreui/coreui-react#366]
Hi,

Since using the beta site the CModal has stopped loading. Is there some styling changes I need to add?

**Comment by mrholek** [comment]
Please show me your code.

**Comment by karls4** [comment]
Top component has the modal component wrapped to only show it when needed
![image](https://github.com/coreui/coreui-react/assets/22108543/3871effb-f283-4c76-86b9-06d7db4efc4e)

I had to add backdrop="static" to get it to stay, the modal was closing straight away without any user input
![image](https://github.com/coreui/coreui-react/assets/22108543/17bcf39a-ccf3-49dd-afee-dd49c040a6d6)

Its working now after adding the static backdrop.

**Comment by kimkong88** [comment]
experiencing same issue. adding static backdrop worked, but it isn't what we want to do. I've updated to v5 alpha accidentally thought it was working well until i see this :(

**Comment by mrholek** [comment]
Do you have this problem in v4.9.1?

**Comment by kimkong88** [comment]
> Do you have this problem in v4.9.1?

I can test when I have capacity. I am currently using 5.0.0-alpha.0. seems to be stable for now except modal.

**Comment by kimkong88** [comment]
Checked with v4.9.1 and it works perfectly. I also rolled back to this version as seems far more stable.
