### ISSUE TITLE
element-closest causes issues in isomorphic application

### ISSUE THREAD

**Issue by dubvfan87** [coreui/coreui-react#37]
The package element-closest causes issues in an isomorphic application because the server does not have window.Element.

There is a fix which makes element-closest a no-op on the server side -> 
"element-closest": "github:ptolemybarnes/closest",

**Comment by fitz-ez** [comment]
Have you found a work around for this @dubvfan87? My Nextjs app crashes even when I dynamically import components that use element-closest and also only render when I've check for typeof window !== "undefined".

**Comment by xidedix** [comment]
hi @dubvfan87 @fitz-ez 
please update `@coreui/react` to `v2.1.2` and let us know if this works for you

**Comment by raitucarp** [comment]
getComputedStyle not working in SSR especially Next.js

**Comment by woothu** [comment]
The issue should be solved in version 3
