### ISSUE TITLE
CTooltip removes the style before the hide animation completes

### ISSUE THREAD

**Issue by rtsoftplzen** [coreui/coreui-react#375]
Hi,

CTooltip removes the style immediately when it is hidden. Before the element is removed, the tooltip flashes at the end of the body (the animation for hiding runs at the end of the body, instead of above the source element). In javascript version this is fine, the style is removed after the animation is finished.

Window 11, Microsoft Edge (116.0.1938.69)

Thank you in advance.

![coreui-react-ctooltip](https://github.com/coreui/coreui-react/assets/24958302/1fd9389f-6a50-46ec-87bd-b3562f5209e6)

**Comment by mrholek** [comment]
@rtsoftplzen fixed in `@coreui/react@4.10.0` / `@coreui/react-pro@4.13.0`

**Comment by rtsoftplzen** [comment]
@mrholek thanks for the fix.

It's better, now you can see the animation for "fade". But still after the animation is finished, style properties are removed before the element is removed from the DOM.

We have now fixed it for ourselves with .tooltip:not([style*="position"]) {display: none;}.

Have a nice day.

**Comment by mrholek** [comment]
Now it works as in the Vanilla JS version. We added a transition end listener, so the Popper.js instance is destroyed after the fade animation.
