### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Alan-Gomes** [coreui/coreui-react#378]
I am getting this error using CTooltip with `@coreui/react 4.10.0` and `react 18.2.0`

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition2 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```

After some investigation, it looks like the issue comes from this [specific part of the implementation](https://github.com/coreui/coreui-react/blob/main/packages/coreui-react/src/components/tooltip/CTooltip.tsx#L154). The `CTooltip` component is not passing the `nodeRef` prop [as required by the `Transition` element](https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L225) to not use `findDOMNode`.

Although I found the cause of the error, I don't have enough knowledge about the project's architecture to open a pull request. Thanks for the support.

**Comment by mrholek** [comment]
@Alan-Gomes fixed. Upgrade `@coreui/react 4.10.1`
