### ISSUE TITLE
Remove sidebar Toggler button from AppHeader

### ISSUE THREAD

**Issue by CarlosGabrielTovar1991** [coreui/coreui-react#38]
Greetings! You did an excellent template.

My app doesn't need to show the sidebar toggler button in large/medium screens. I was thinking I can achieve this with a prop, but doesn't work. Something like this:

`<AppHeader sidebarToggler={false} fixed> ... </AppHeader>`

how can I remove it?

**Comment by xidedix** [comment]
hi @CarlosGabrielTovar1991 
Maybe [bootstrap display utilities](https://getbootstrap.com/docs/4.1/utilities/display/) will help?
sth like `<AppSidebarToggler className="d-lg-none" />` in DefaultLayout.js

**Comment by CarlosGabrielTovar1991** [comment]
> hi @CarlosGabrielTovar1991
> Maybe [bootstrap display utilities](https://getbootstrap.com/docs/4.1/utilities/display/) will help?
> sth like `<AppSidebarToggler className="d-lg-none" />` in DefaultLayout.js

You are right! OGM I was so stupid. Removing the following line in DefaultLayout.js

`<AppSidebarToggler className="d-md-down-none" display="lg" />`

Exactly what I want! Thanks friend and excuse me for so silly question.
