### ISSUE TITLE
after cloning the react repository, cannot "Start" - Script "Start" missing

### ISSUE THREAD

**Issue by mveemedia** [coreui/coreui-react#381]
hello, 

I'd love to try your free react admin template. I was trying to run it locally after running "git clone" react repository and after npm install in root directory. 

When I run "npm start" I'd get this error:

npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

I tried running the command from root folder. 

Please bear in mind i'm not very savvy, and trying to learn. I've scowered the net for hours trying to find the issue, however all videos and guides have the same process: npm install, npm start. However the newest is a year old. 

Any help on this would be immensely appreciated! 

Thank you in advance. 
Mark.

**Comment by jasperfirecai2** [comment]
npm *run* start. start is not a builtin method. it's a named run configuration
