### ISSUE TITLE
CMultiSelect Triggers even on outside activity

### ISSUE THREAD

**Issue by hamzatahir-notell** [coreui/coreui-react#392]
CMultiselect even triggers with outside activity... 
i even applied a check 
If (selected ) {}
but still calls wven with outside activity
any help?

**Comment by mrholek** [comment]
@hamzatahir-notell do you use version 4 or 5?

**Comment by hamzatahir-notell** [comment]
@mrholek my version is "@coreui/coreui-pro": "^4.1.2", "@coreui/react-pro": "^4.1.4",  react version 17
