### ISSUE TITLE
Improve CDatePicker manual input with mask/segmented input

### ISSUE THREAD

**Issue by ewgenym** [coreui/coreui-react#394]
Manual date input is essential because of `input type="date"` limitations, especially in mobile browsers.
However, at the moment, it is hard for users to input date manually because
1. User has to remember and input format delimiters
2. Date segments are not validated (max 12 in month segment, etc.)

An example of how it might look like is: https://mui.com/x/react-date-pickers/date-picker/

**Comment by mrholek** [comment]
@ewgenym it's something we have on our roadmap.

**Comment by ewgenym** [comment]
Great, thanks.
Could you give an idea of approx. release/date it is planned to be included?

**Comment by nicolak** [comment]
Hi. Is there any news on this?
