### ISSUE TITLE
Performance Issues with CDatePicker Component when using timepicker Prop

### ISSUE THREAD

**Issue by hamzatahir-notell** [coreui/coreui-react#401]
In our React application, we have integrated multiple instances of the CDatePicker component from the CoreUI library. When we enable the timepicker prop to allow users to select both date and time, and have 20 or more instances of the component on a single page, we observe significant performance degradation. This issue manifests as:

Delayed Click Handlers: Interactions such as button clicks and other event handlers experience noticeable delays.
UI Lag: The responsiveness of the entire user interface is compromised, making it sluggish and unresponsive at times.
Steps to Reproduce:

Integrate 20 or more instances of the CDatePicker component in a CoreUI React project.
Enable the timepicker prop for each instance.
Observe the overall performance of the application, particularly focusing on click handlers and general UI responsiveness.
Expected Behavior:
The CDatePicker component with the timepicker prop enabled should function smoothly without causing any performance issues. Click handlers and other interactions should remain responsive, even with multiple instances on a single page.

Actual Behavior:
Enabling the timepicker prop with 20 or more instances of the CDatePicker component results in delayed click handlers and a sluggish user interface.

Environment:

 @coreui/react-pro : "^4.1.4",
 @coreui/coreui-pro : "^4.1.2",
 react : "^17.0.2",
Browser: Chrome , Firefox (latest)
Operating System: Windows10
Additional Information:
We have tried several troubleshooting steps, including:

Profiling the application to identify performance bottlenecks.
Testing on different browsers and devices.
Ensuring there are no additional heavy processes running concurrently.
Despite these efforts, the issue persists. Any guidance or fixes would be highly appreciated.
![SS](https://github.com/coreui/coreui-react/assets/129175362/89164072-e741-443b-a58b-b4c81a28d0d4)

**Comment by mrholek** [comment]
Hi, can you update `@coreui/react-pro` to the latest version and check if this issue still exists. Version 4.1.4 is outdated. Please update also react to the latest version
