### ISSUE TITLE
Getting an error related with options in MultiSelect

### ISSUE THREAD

**Issue by paskibiorem** [coreui/coreui-react#415]
**OS:** Manjaro | **Browser:** Microsoft Edge **Version:** 132.0.2917.0

I'm getting an error related with the CoreUI MultiSelect. First of all I have an array of items with data charged from an API. This is important because I can load static data, but dynamically nope (coming from the API).

The point is I'm getting the following error, knowing that my array loads correctly the data and other similar components like [react-multi-select-component](https://www.npmjs.com/package/react-multi-select-component) work perfectly fine.

Waiting a response!

![Screenshot from 2024-11-12 18-10-29](https://github.com/user-attachments/assets/a137176f-48c8-4d91-b307-97d6902748fc)

**Comment by mrholek** [comment]
@paskibiorem for PRO components, we have dedicated support. Please use this form - https://coreui.io/support/

**Comment by paskibiorem** [comment]
That would be wonderful c:

![image](https://github.com/user-attachments/assets/34e47cdf-5d26-467b-85ac-1e5ab682c1b4)

**Comment by mrholek** [comment]
Please send it to support@coreui.io
