### ISSUE TITLE
SidebarNav - subcomponent: item

### ISSUE THREAD

**Issue by marciokuroki** [coreui/coreui-react#43]
I'm using SidebarNav, implement a navConfig strutured as the document show us. But I'd like to use "target: '_blank'" in a item to open the link in a new tab. How could I do that?

**Comment by DannyAllegrezza** [comment]
Looking for assistance here as well. I've tried a few different approaches, but none of them seem to work out nicely. All I want to do is generate an anchor tag with the `target='_blank'` attribute attached to it. :-1:

**Comment by xidedix** [comment]
hi @marciokuroki @DannyAllegrezza 

please update:
- `@coreui/coreui` to `2.1.0`
- `@coreui/react` to `2.1.0`

usage example: 
```json
{
  name: 'Try CoreUI PRO',
  url: 'https://coreui.io/pro/react/',
  icon: 'cui-layers icons',
  variant: 'danger',
  attributes: { target: '_blank', rel: "noopener" },
},
```

**Comment by marciokuroki** [comment]
@xidedix thanks!
