### ISSUE TITLE
How to remove # from url?? 

### ISSUE THREAD

**Issue by shashibeit** [coreui/coreui-react#46]
When I load dashboard it appears as http://localhost:3000/#/dashboard 
So How can we remove that # from URL

**Comment by xidedix** [comment]
hi @shashibeit 
The current version of CoreUI for React template uses [`<HashRouter>`](https://reacttraining.com/react-router/web/api/HashRouter). You can switch to [`<BrowserRouter>`](https://reacttraining.com/react-router/web/api/BrowserRouter) if you prefer.

Changes have to be made at least in [./src/App.js](https://github.com/coreui/coreui-free-react-admin-template/blob/master/src/App.js) and wherever `#` paths are in use (if any).

**Comment by sasaahlan** [comment]
Hi @xidedix 
I just bought and experience the same.
I am trying coreui-pro-angular-admin-template-2.2.0
Any idea to remove # ?
Thanks

**Comment by xidedix** [comment]
hi @sasaahlan 
your issue has been moved to https://github.com/coreui/coreui-angular/issues/37

**Comment by dyankastutara** [comment]
change HashRouter to BrowerRouter on src/App.js

**Comment by ayoub-ouichen** [comment]
> When I load dashboard it appears as http://localhost:3000/#/dashboard So How can we remove that # from URL

Go to app.modules.ts and let providers LocationStrategy & HashLocationStrategy in a comment like this:
  providers: [
    // {
    //   provide: LocationStrategy,
    //   useClass: HashLocationStrategy
    // },
    IconSetService,
  ],
