### ISSUE TITLE
How to toggle light/dark theme?

### ISSUE THREAD

**Issue by jknapp25** [coreui/coreui-react#47]
I see that there was a question about enabling the dark theme, but how would one go about making that a toggleable feature? So then users could choose light or dark.

**Comment by xidedix** [comment]
There is no theme toggler at the moment. We are planning this feature for future releases.

**Comment by jknapp25** [comment]
Gotchya, any suggestions on how to go about that myself?

**Comment by tjbartram** [comment]
@jknapp25 Hi, I've been looking for some pointers on this as well. Did you happen to get anywhere with this?

**Comment by jmandivarapu1** [comment]
is there any ideas or solution on how tp do this?

**Comment by woothu** [comment]
`coreui-pro-react-admin-template` v3 has ready to use toggle solution
