### ISSUE TITLE
Need to change asidemenutoggler 

### ISSUE THREAD

**Issue by sasaahlan** [coreui/coreui-react#51]
Greetings! It's excellent template.
I need to change asidemenutoggler with notification badge.
How to do this?
Thanks

**Comment by xidedix** [comment]
hi @sasaahlan 
Why don't you pass customized children to `AppAsideToggler`, 
in `src/containers/DefaultLayout/DefaultHeader.js` roughly sth like this:
```jsx
<AppAsideToggler className="d-md-down-none">
  <span className="navbar-toggler-icon"></span>
  <Badge pill color="danger" style={{position: 'absolute', top: '20%', marginLeft: '-1em', marginRight: '-1em', fontSize: '10.5px'}}>5</Badge>
</AppAsideToggler>
```

**Comment by sasaahlan** [comment]
hi @xidedix 
Apologize I am not expert in angular. There is not src/containers folder.
Do you mean, I need to create DefaultHeader.js in src/app/containers/default-layout using the above code ? Then where do I need to insert DefaultHeader.js ?
thanks

**Comment by xidedix** [comment]
@sasaahlan 
whoops! you mean angular 
please disregard my answer above, since this is about `@coreui/react` version

**Comment by sasaahlan** [comment]
@xidedix
Ok will wait your guidance. 
Thanks

**Comment by sasaahlan** [comment]
Also I need help on how to link between notification with badge, with respective tab in asidemenu like attached image. Thanks.

![image](https://user-images.githubusercontent.com/479071/50448838-0a877e00-0956-11e9-958f-e42d782739df.png)
