### ISSUE TITLE
How to switch Pro version to "Alba" colors?

### ISSUE THREAD

**Issue by pbenschop** [coreui/coreui-react#57]
We purchased CoreUI Pro React.js and it is working well for us. Instead of the default SideBar with the dark background, we would like to use the colors in the SideBar version in the "Alba" template that has the white background. Do we need to purchase the Alba React.js Admin Template also or is there a way  to easily switch to the Alba colors?

**Comment by woothu** [comment]
We don't have specific 'ALBA' colors theme
