### ISSUE TITLE
data-size LaddaButton don't work

### ISSUE THREAD

**Issue by yuriedmundo** [coreui/coreui-react#64]
Property data-size dont work in react

`<LaddaButton
                          className="btn btn-success btn-ladda"
                          loading={this.state.expLeft}
                          onClick={() => this.toggle('expLeft')}
                          data-color="green"
                          data-style={EXPAND_LEFT}
                          data-size={XS}>
                          Consultar
                        </LaddaButton>`

![Captura de Tela 2019-04-05 às 15 32 41](https://user-images.githubusercontent.com/5764593/55648978-189c3480-57b8-11e9-9187-117f4dc97f69.png)

**Comment by xidedix** [comment]
thanks @yuriedmundo 

HTML5 semantic elements IE11: _Partial support refers to only the `<main>` element (added later to the spec) being "unknown", though **it can still be used and styled**._

see: https://caniuse.com/#feat=html5semantic

**Comment by xidedix** [comment]
confirmed
