### ISSUE TITLE
AppSwitch does not support boolean values

### ISSUE THREAD

**Issue by alex-woodall-premierfoods** [coreui/coreui-react#66]
I've got a CoreUI Pro (Clever) project I'm working on, I'm trying to use an AppSwitch component in a form that updates values from a mongoDB document that has a boolean value in the given field. This would appear to be the primary use case for a Switch, but the "value" prop only supports string values, so I get the error message both when the form is rendered and when the switch is flipped on and off:

Warning: Failed prop type: Invalid prop `value` of type `boolean` supplied to `AppSwitch`, expected `string`

There does not appear to be any documentation in the docs area about what props do what for AppSwitch.

Please advise the best way to bind a boolean form value to this component.

**Comment by xidedix** [comment]
hi @alex-woodall-premierfoods 

The `value` attribute specifies the value of an `<input>` element - this is the value that is sent and has meaning when submitting a form only. (name="value").

To flip the switch on and off, use `checked` property instead.

**Comment by alex-woodall-premierfoods** [comment]
Many thanks, that worked, I'm a big fan of CoreUI, but as a customer, if I'm honest, the documentation needs some work, I appreciate that fixing bugs usually takes precedence over documentation but it does make it tricky when as a developer you can't tell what does what.

**Comment by xidedix** [comment]
@alex-woodall-premierfoods thanks for the follow-up 
we are working on the next version and improved docs
