### ISSUE TITLE
SidebarNav requires location prop

### ISSUE THREAD

**Issue by e-burlaka-md** [coreui/coreui-react#69]
It would be great to add this prop to propTypes object
 
package.json
```json
"dependencies": {
    "@coreui/coreui": "^2.1.9",
    "@coreui/react": "^2.1.5",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "..."
  },
```

![localhost_3000](https://user-images.githubusercontent.com/20064867/56810832-ed998380-683f-11e9-8193-c163128e14fe.png)

![console](https://user-images.githubusercontent.com/20064867/56810858-00ac5380-6840-11e9-90bc-4a8ef244db67.png)

**Comment by xidedix** [comment]
Hi @e-burlaka-md 
Could you please provide us some details regarding the issue? 
Is this an error report or an enhancement request?

**Comment by e-burlaka-md** [comment]
It is an enhancement request, in the example below you pass all props from Route component to AppSidebarNav
I forget to do that and got the error, it took me some time to understand what prop do I need to pass to AppSidebarNav
Someday this improvement save the time to someone

[DefaultLayout.js](https://github.com/coreui/coreui-free-react-admin-template/blob/e5d84e0fc7ae84902e61dffee2d6e2bb9b378485/src/containers/DefaultLayout/DefaultLayout.js#L48)

**Comment by mankutila** [comment]
Also encountered that issue. Fixed by wrapping `DefaultLayout` with `withRouter`.

**Comment by woothu** [comment]
In v3 giving the location is no longer necessary
