### ISSUE TITLE
SidebarNav: example of how to implement progress bar in SidebarNav?

### ISSUE THREAD

**Issue by MaxOrelus** [coreui/coreui-react#71]
The demo shows progress bars within the sidebar under system utilization. I was wondering how can I embed JSX render for the progress bars similar to the demo? The examples shown in the README shows how to change the element tag, but I was wondering if there was a way to embed a component such as the progress bar?

Warm regards,
Max

**Comment by woothu** [comment]
You can place any component you want inside the sidebar.
