### ISSUE TITLE
Always getting redirected to /dashboard

### ISSUE THREAD

**Issue by Daavidaviid** [coreui/coreui-react#73]
Hi,

I bought the PRO version, so I have been using it lately. There is both the complete example and the starter example in the downloaded folder.

I encounter an issue when I try add a second view from the starter example.
I add it both to `routes.js` and `_nav.js`. The issue is that everytime I click on it from the navigation panel I get redirected to `/dashboard`.

And when I check with the developer mode I can see that in the complete example there is a `PUSH` action in the history while in the starter example there is a `REPLACE`.

I'm still digging into it, I'll keep you updated.

**Comment by woothu** [comment]
This is `react-router` related issue
