### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by Golddragon0614** [coreui/coreui-react#76]
@coreui\react\lib\Shared\layout\layout.js
document is not defined.how to solve it?

**Comment by Golddragon0614** [comment]
@coreui\react\lib\Shared\layout\layout.js
document is not defined

**Comment by kevinashworth** [comment]
I am seeing same problem. Seeking workarounds/fixes! Thanks...

**Comment by VyacheslavKazadaev** [comment]
Hello everyone. Has anyone been able to fix this?

**Comment by VyacheslavKazadaev** [comment]
@kevinashworth Hello! Has anyone been able to fix this?

**Comment by kevinashworth** [comment]
I am not aware of a fix. I'm still awaiting v3. 

In November 2019, they messaged me about `layout.js`:

> This is the follow-up.
> 
> Please disregard the previous message.
> We can confirm the issue:

> > (node:12708) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
> >     at Object.<anonymous> (node_modules/@coreui/react/lib/Shared/layout/layout.js:62:27)

> 
> 
> We'll try to fix this in the next version of CoreUI 3 for React and port it back to v2 if possible.
> 
> Thanks for the heads-up.
> 
> CoreUI Team.

**Comment by VyacheslavKazadaev** [comment]
@kevinashworth Thank you!

**Comment by woothu** [comment]
Version 3 is now released, please let us know if you still have issues regarding SSR.
