### ISSUE TITLE
How to toggle light/dark theme?

### ISSUE THREAD

**Issue by jmandivarapu1** [coreui/coreui-react#78]
Hi,

If anybody did please let me know on how to do it? Like have a button from which we can just toggle dark and light mode?

Regards,
Jay

**Comment by jmandivarapu1** [comment]
is there any update on this?

**Comment by ehtisham91** [comment]
> is there any update on this?

So, did you find any solution?  I've been looking for some guides/solutions on this as well.

**Comment by iaminawe** [comment]
Also following this - just bought the React Pro team package and it does not seem to have the dark mode switching feature yet.

**Comment by woothu** [comment]
`coreui-pro-react-admin-template` v3 has ready to use toggle solution
