### ISSUE TITLE
how to give click function for AppSidebarNav

### ISSUE THREAD

**Issue by yoginitheesh** [coreui/coreui-react#79]

**Comment by hdjvieira** [comment]
As described [here](https://github.com/coreui/coreui-react/blob/master/src/SidebarNav.md#navconfig-shape) there is an optional attributes property for Items in navConfig, so it is possible to add an onClick attribute.

This next example is to prevent reloading the current page:

```javascript
{
  name: 'Dashboard',
  url: '/dashboard',

  attributes: {
    onClick: e => {
      if (history.location.pathname === "/dashboard") {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }
      return true;
    }
  }
}
```
