### ISSUE TITLE
Toggle Dark Mode

### ISSUE THREAD

**Issue by jmandivarapu1** [coreui/coreui-react#81]
Hi,

If anybody did please let me know on how to do it? Like have a button from which we can just toggle dark and light mode?

Regards,
Jay

**Comment by xidedix** [comment]
Hi @jmandivarapu1 

We are going to introduce the light/dark mode toggler as a new feature for incoming CoreUI Pro v3. Stay tuned.

**Comment by jmandivarapu1** [comment]
Hey I  bought coreUI v2 react. will I get the CoreUI v3 react or how does I can upgrade?
