### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'setTargetNode' of undefined

### ISSUE THREAD

**Issue by Harish-singh33** [coreui/coreui-react#85]
I am getting this issue when updating new version of "@coreui/react": "^2.0.8",  2.0.8 is working fine.
So apps breaking because of:
 Warning: Failed context type: The context `isOpen` is marked as required in `DropdownToggle`, but its value is `undefined`.
    in DropdownToggle 
    in li (created by Dropdown)
    in Manager (created by Dropdown)
    in Dropdown (created by AppHeaderDropdown)
    in **AppHeaderDropdown**
![Screenshot 2019-08-08 at 12 20 16 PM](https://user-images.githubusercontent.com/1620600/62681868-56180500-b9d8-11e9-825b-72f83e2366be.png)

**Comment by xidedix** [comment]
Hi @Harish-singh33 

in `src/containers/DefaultLayout/DefaultHeader.js` change 
```jsx
<AppHeaderDropdown direction="down">
```

to 
```jsx
<UncontrolledDropdown nav direction="down">
```

UncontrolledDropdown does not require `isOpen` nor `toggle` props to work.

**Comment by globalfarmer** [comment]
Hi,

I got the same problem and I fixed that by do not update react, so I use tilde ("~") instead of caret ("^" ) before the coreui/react version number.

```
e.g:
 "@coreui/react": "^2.0.8" ->  "@coreui/react": "~2.0.8"
```

**Comment by sturm3nta** [comment]
I solved it thanks to this comment -> https://stackoverflow.com/a/57903640, updating the reactstrap version from "7.1.0" to "8.4.1"
