### ISSUE TITLE
How to use custom SVG icons in the SidebarNav?

### ISSUE THREAD

**Issue by joao-cesar** [coreui/coreui-react#86]
Hi.

It seems that the component only accepts class names for CSS. But how do I use my own SVG icons?

**Comment by irtzasuhail** [comment]
Has there been any progress on this? Or any workaround?

**Comment by woothu** [comment]
In v3 there is a possibility of passing SVG/JS icons to the sidebar

**Comment by alekhya-cloudstok** [comment]
Were you able to use custom icons in the sidenav? I'm facing the same issue in angular.
