### ISSUE TITLE
Accordion react-bootstrap bug

### ISSUE THREAD

**Issue by theocerutti** [coreui/coreui-react#87]
Hello,

I just want let you know there is a little bug with coreui react and accordion of react-bootstrap.
Have a look:

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/44285344/65129073-d3e21e00-da24-11e9-8f75-1b68da37e9d2.png)

**Comment by xidedix** [comment]
@theocerutti 
Thanks for the heads-up!

**Comment by woothu** [comment]
In v3 we use our own CCollapse component
