### ISSUE TITLE
Documentation on how to toggle

### ISSUE THREAD

**Issue by gravitymedianet** [coreui/coreui-react#97]
I am a core UI Pro customer. I am looking for a simple way to toggle the sidebar, aside etc. from my app without having to rewrite your components. I am using Mobx for state management so I need to be able to link into the components and hide/show sidebar/aside from different parts of the app.

I was previously told to simply add a class to the HTML however, this causes an issue with the state of the component; it reverses the toggler or the minimizers.

Please let me know how to provide a way to set a toggle method prop to components or even a  property isOpen or something which overrides the default toggle functionality.

Thank you

**Comment by Metzen2k** [comment]
@gravitymedianet Did you ever figure this out? I'm using mobx-state-tree and mobx-state-tree-router and am trying to get it to work without starting from scratch on navigation.

**Comment by woothu** [comment]
Does toggle solution from template version 3.0.0 help you?

**Comment by gravitymedianet** [comment]
@woothu It is not an option as I cannot upgrade the package. I am using version 2.

**Comment by woothu** [comment]
Our upgrade in version 2 will most probably cause a breaking change, and this is a very specific case so I am marking this issue as wontfix

**Comment by jknapp25** [comment]
I also need this
