### ISSUE TITLE
Navigate to route on AppSideBarNav parent menu click.

### ISSUE THREAD

**Issue by regimani** [coreui/coreui-react#98]
Currently when user click on the parent menu item, it just toggle and display/hide the child menu items. The href is being hard coded to # for the  dropdown component.  Is there a way to set a url for the parent dropdown menu item?

**Comment by xidedix** [comment]
@regimani 
To override the default behavior of `nav-dropdown toggle` and navigate to `url` use custom `onClick` method:
```json5
{
  name: 'Base',
  url: '/base',
  icon: 'icon-puzzle',
  attributes: {onClick: (e, item)=>{ console.log(e, item) }}, // (v2.5.6 up) optional
  children: []
}
``` 
For active route consistency, you can set redirect on partial routes in `src/routes.js`: 
```js
import { Redirect } from 'react-router-dom';
...
const routes = [
  ...
  { path: '/base', exact: true, name: 'Base', component: () => <Redirect to={'/base/cards'}/> },
  { path: '/base/cards', name: 'Cards', component: Cards },
  { path: '/base/forms', name: 'Forms', component: Forms },
  ...
]
```
