### ISSUE TITLE
I'm started working on Coreui 3 version 

### ISSUE THREAD

**Issue by majsterkoo** [coreui/coreui-react#99]
Hi, because there is no any activity about implementing new coreui 3 version I decided to start work on it. It's for my needs, but If we are interested, I Can create pull request after migration will be done. I expect first "beta" release until the end of the week. [my github link](https://github.com/majsterkoo/coreui-react)

There are some minor internal changes, but there are breaking changes too. There are needs to modify "DefaultLayout" component, because there are (in coreui 3) some elements changes (other position of sidebars etc).

If someone started working on new version too, please notify me, so as I'm not working on duplicity things...

Have a nice day!

**Comment by xidedix** [comment]
Hi @majsterkoo 
Thanks for your efforts.
We are targeting to disclose public alpha release of CoreUI v3 for React later this week, I am afraid.

**Comment by majsterkoo** [comment]
Hi, 
Thanks for response. So, I'm closing this issues. 
I look forward to the official version.

**Comment by majsterkoo** [comment]
Because it is long time and there isn't still coreui 3 react version and now, I need it for new project, I resume to work on my fork of coreui-react. Now I have mostly implemented header (without dropdowns), breadcumbs and right sidebar. In whitch status is your coreui-react 3 @xidedix ? I can modify other components and then create pull request. You can inspire, or accept it or what you want... But if you are mostly done in migration, I'll rewrite only needed thinks for my needs and wait for oficial release... Thanks for response

**Comment by kevinashworth** [comment]
Following

**Comment by majsterkoo** [comment]
Basic template is now working. Need code cleaning and testing with special parameters (sizes etc).
![image](https://user-images.githubusercontent.com/3364720/78991805-1478c480-7b3a-11ea-8669-45d285a7a98b.png)
![image](https://user-images.githubusercontent.com/3364720/78991821-1e9ac300-7b3a-11ea-9179-d3db8130d12b.png)
